-- lvl 200 (beide)
-- Noisetier, Ebène, Orme, Charme, Tremble, Frostiz

ELEMENTS_TO_GATHER = {259, 29, 30, 32, 133, 134}

MAX_MONSTERS = 1

MAX_PODS = 95

function move()
	return {
        -- Frigost route
		{map = "-78,-41", changeMap = "top"},
		{map = "-78,-42", changeMap = "top"},
		{map = "-78,-43", changeMap = "left"},
		{map = "-79,-43", changeMap = "left"},
		{map = "-80,-43", changeMap = "left"},
		{map = "-81,-43", changeMap = "left"},
		{map = "-82,-43", changeMap = "left"},
		{map = "-83,-43", changeMap = "left"},
		{map = "-84,-43", changeMap = "left"},
		{map = "-85,-43", changeMap = "top"},
		{map = "-85,-44", changeMap = "top"},
		{map = "-85,-45", gather = true, custom = wait, changeMap = "top"},
		{map = "-85,-46", changeMap = "right"},
		{map = "-84,-46", gather = true, custom = wait, changeMap = "top"},
		{map = "-84,-47", changeMap = "right"},
		{map = "-83,-47", gather = true, custom = wait, changeMap = "right"},
		{map = "-82,-47", gather = true, custom = wait, changeMap = "right"},
		{map = "-81,-47", changeMap = "top"},
		{map = "-81,-48", changeMap = "right"},
		{map = "-80,-48", changeMap = "right"},
		{map = "-79,-48", changeMap = "bottom"},
		{map = "-79,-47", changeMap = "right"},
		{map = "-78,-47", gather = true, custom = wait, changeMap = "right"},
		{map = "-77,-47", gather = true, custom = wait, changeMap = "right"},
		{map = "-76,-47", gather = true, custom = wait, changeMap = "right"},
		{map = "-75,-47", changeMap = "top"},
		{map = "-75,-48", changeMap = "top"},
		{map = "-75,-49", gather = true, custom = wait, changeMap = "right"},
		{map = "-74,-49", changeMap = "right"},
		{map = "-73,-49", gather = true, custom = wait, changeMap = "top"},
		{map = "-73,-50", changeMap = "top"},
		{map = "-73,-51", changeMap = "top"},
		{map = "-73,-52", changeMap = "left"},
		{map = "-74,-52", gather = true, custom = wait, changeMap = "top"},
		{map = "-74,-53", changeMap = "top"},
		{map = "-74,-54", gather = true, custom = wait, changeMap = "right"},
		{map = "-73,-54", changeMap = "bottom"},
		{map = "-73,-53", gather = true, custom = wait, changeMap = "right"},
		{map = "-72,-53", changeMap = "top"},
		{map = "-72,-54", gather = true, custom = wait, changeMap = "right"},
		{map = "-71,-54", changeMap = "right"},
		{map = "-70,-54", changeMap = "right"},
		{map = "-69,-54", changeMap = "right"},
		{map = "-68,-54", changeMap = "top"},
		{map = "-68,-55", changeMap = "top"},
		{map = "-68,-56", changeMap = "top"},
		{map = "-68,-57", changeMap = "top"},
		{map = "-68,-58", changeMap = "top"},
		{map = "-68,-59", changeMap = "top"},
		{map = "-68,-60", gather = true, custom = wait, changeMap = "right"},
		{map = "-67,-60", changeMap = "right"},
		{map = "-66,-60", changeMap = "right"},
		{map = "-65,-60", gather = true, custom = wait, changeMap = "right"},
		{map = "-64,-60", gather = true, custom = wait, changeMap = "top"},
		{map = "-64,-61", changeMap = "top"},
		{map = "-64,-62", changeMap = "left"},
		{map = "-65,-62", changeMap = "top"},
		{map = "-65,-63", gather = true, custom = wait, changeMap = "right"},
		{map = "-64,-63", gather = true, custom = wait, changeMap = "right"},
		{map = "-63,-63", changeMap = "right"},
		{map = "-62,-63", changeMap = "right"},
		{map = "-61,-63", changeMap = "top"},
		{map = "-61,-64", gather = true, custom = wait, changeMap = "right"},
		{map = "-60,-64", changeMap = "right"},
		{map = "-59,-64", changeMap = "right"},
		{map = "-58,-64", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-58,-63", changeMap = "bottom"},
		{map = "-58,-62", changeMap = "bottom"},
		{map = "-58,-61", changeMap = "left"},
		{map = "-59,-61", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-59,-60", changeMap = "right"},
		{map = "-58,-60", changeMap = "right"},
		{map = "-57,-60", changeMap = "bottom"},
		{map = "-57,-59", gather = true, custom = wait, changeMap = "right"},
		{map = "-56,-59", changeMap = "right"},
		{map = "-55,-59", changeMap = "bottom"},
		{map = "-55,-58", changeMap = "bottom"},
		{map = "-55,-57", gather = true, custom = wait, changeMap = "left"},
		{map = "-56,-57", changeMap = "left"},
		{map = "-57,-57", changeMap = "bottom"},
		{map = "-57,-56", gather = true, custom = wait, changeMap = "left"},
		{map = "-58,-56", changeMap = "left"},
		{map = "-59,-56", changeMap = "bottom"},
		{map = "-59,-55", changeMap = "bottom"},
		{map = "-59,-54", changeMap = "right"},
		{map = "-58,-54", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-58,-53", changeMap = "left"},
		{map = "-59,-53", changeMap = "left"},
		{map = "-60,-53", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-60,-52", changeMap = "bottom"},
		{map = "-61,-51", changeMap = "left"},
		{map = "-62,-51", changeMap = "left"},
		{map = "-63,-51", changeMap = "left"},
		{map = "-64,-51", changeMap = "bottom"},
		{map = "-64,-50", changeMap = "bottom"},
		{map = "-64,-49", gather = true, custom = wait, changeMap = "left"},
		{map = "-65,-49", changeMap = "bottom"},
		{map = "-65,-48", changeMap = "bottom"},
		{map = "-65,-47", gather = true, custom = wait, changeMap = "left"},
		{map = "-66,-47", gather = true, custom = wait, changeMap = "top"},
		{map = "-66,-48", gather = true, custom = wait, changeMap = "left"},
		{map = "-67,-48", changeMap = "bottom"},
		{map = "-67,-47", changeMap = "left"},
		{map = "-68,-47", changeMap = "left"},
		{map = "-69,-47", changeMap = "left"},
		{map = "-70,-47", changeMap = "left"},
		{map = "-71,-47", gather = true, custom = wait, changeMap = "left"},
		{map = "-72,-47", gather = true, custom = wait, changeMap = "left"},
		{map = "-73,-47", changeMap = "bottom"},
		{map = "-73,-46", gather = true, custom = wait, changeMap = "right"},
		{map = "-72,-46", gather = true, custom = wait, changeMap = "right"},
		{map = "-71,-46", gather = true, custom = wait, changeMap = "right"},
		{map = "-70,-46", changeMap = "bottom"},
		{map = "-70,-45", gather = true, custom = wait, changeMap = "left"},
		{map = "-71,-45", gather = true, custom = wait, changeMap = "left"},
		{map = "-72,-45", gather = true, custom = wait, changeMap = "left"},
		{map = "-73,-45", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-73,-44", gather = true, custom = wait, changeMap = "right"},
		{map = "-72,-44", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-72,-43", changeMap = "right"},
		{map = "-71,-43", gather = true, custom = wait, changeMap = "right"},
		{map = "-70,-43", changeMap = "right"},
		{map = "-69,-43", changeMap = "bottom"},
		{map = "-69,-42", gather = true, custom = wait, changeMap = "left"},
		{map = "-70,-42", changeMap = "bottom"},
		{map = "-70,-41", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-70,-40", gather = true, custom = wait, changeMap = "right"},
		{map = "-69,-40", gather = true, custom = wait, changeMap = "right"},
		{map = "-68,-40", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-68,-39", gather = true, custom = wait, changeMap = "left"},
		{map = "-69,-39", changeMap = "left"},
		{map = "-70,-39", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-70,-38", changeMap = "right"},
		{map = "-69,-38", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-69,-37", gather = true, custom = wait, changeMap = "left"},
		{map = "-70,-37", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-70,-36", changeMap = "right"},
		{map = "-69,-36", changeMap = "bottom"},
		{map = "-69,-35", gather = true, custom = wait, changeMap = "left"},
		{map = "-70,-35", changeMap = "left"},
		{map = "-71,-35", changeMap = "bottom"},
		{map = "-71,-34", gather = true, custom = wait, changeMap = "left"},
		{map = "-72,-34", changeMap = "left"},
		{map = "-73,-34", changeMap = "left"},
		{map = "-74,-34", changeMap = "top"},
		{map = "-74,-35", changeMap = "top"},
		{map = "-74,-36", changeMap = "top"},
		{map = "-74,-37", changeMap = "top"},
		{map = "-74,-38", changeMap = "top"},
		{map = "-74,-39", changeMap = "top"},
		{map = "-74,-40", changeMap = "top"},
		{map = "-74,-41", changeMap = "left"},
		{map = "-75,-41", changeMap = "left"},
		{map = "-76,-41", changeMap = "left"},
		{map = "-77,-41", changeMap = "left"},
        -- Otomai
		{map = "-51,20", gather = true, custom = wait, changeMap = "left"},
		{map = "-52,20", gather = true, custom = wait, changeMap = "left"},
		{map = "-53,20", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-53,21", gather = true, custom = wait, changeMap = "left"},
		{map = "-54,21", gather = true, custom = wait, changeMap = "top"},
		{map = "-54,20", gather = true, custom = wait, changeMap = "left"},
		{map = "-55,20", gather = true, custom = wait, changeMap = "left"},
		{map = "-56,20", gather = true, custom = wait, changeMap = "top"},
		{map = "-56,19", gather = true, custom = wait, changeMap = "top"},
		{map = "-56,18", gather = true, custom = wait, changeMap = "right"},
		{map = "-55,18", gather = true, custom = wait, changeMap = "top"},
		{map = "-55,17", gather = true, custom = wait, changeMap = "right"},
		{map = "-54,17", gather = true, custom = wait, changeMap = "top"},
		{map = "-54,16", gather = true, custom = wait, changeMap = "left"},
		{map = "-55,16", gather = true, custom = wait, changeMap = "left"},
		{map = "-56,16", gather = true, custom = wait, changeMap = "top"},
		{map = "-56,15", gather = true, custom = wait, changeMap = "top"},
		{map = "-56,14", gather = true, custom = wait, changeMap = "right"},
		{map = "-55,14", gather = true, custom = wait, changeMap = "top"},
		{map = "-55,13", changeMap = "top"},
		{map = "-55,12", gather = true, custom = wait, changeMap = "top"},
		{map = "-55,11", gather = true, custom = wait, changeMap = "top"},
		{map = "-55,10", gather = true, custom = wait, changeMap = "top"},
		{map = "-55,9", gather = true, custom = wait, changeMap = "right"},
		{map = "-54,9", gather = true, custom = wait, changeMap = "right"},
		{map = "-53,9", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-53,10", gather = true, custom = wait, changeMap = "left"},
		{map = "-54,10", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-54,11", changeMap = "right"},
		{map = "-53,11", gather = true, custom = wait, changeMap = "right"},
		{map = "-52,11", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-52,12", gather = true, custom = wait, changeMap = "right"},
		{map = "-51,12", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-51,13", gather = true, custom = wait, changeMap = "left"},
		{map = "-52,13", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-52,14", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-52,15", gather = true, custom = wait, changeMap = "right"},
		{map = "-51,15", gather = true, custom = wait, changeMap = "top"},
		{map = "-51,14", gather = true, custom = wait, changeMap = "right"},
		{map = "-50,14", changeMap = "bottom"},
		{map = "-50,15", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-50,16", gather = true, custom = wait, changeMap = "left"},
		{map = "-51,16", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-51,17", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-51,18", gather = true, custom = wait, changeMap = "bottom"},
		{map = "-51,19", gather = true, custom = wait, changeMap = "bottom"},
	}
end

function bank()
	return {

	}
	end

function emptyInventory()
    npc:npcBank(-1,-1)
    global:delay(2500)
    storage:putAllItems()
    global:leaveDialog()
end

function wait()
    map:waitMovementFinish(5000)
end


function phenix()
	return {
	}
end

function lost()
	return {
	}
end