MAX_PODS = 90

function havresac()
    global:delay(1000)
    global:sendKey(72)
    global:delay(1000)
end

function lost()
	havresac()
end

function hiboux()
    npc:npcBank(-1,-1)
    global:delay(2500)
    storage:putAllItems()
    global:leaveDialog()
end

function astrub()
	global:delay(2500)
	map:changeMap("zaap(125,196,191105026)")
	global:delay(2500)
end

function rivage()
	global:delay(2500)
	map:changeMap("zaap(352,216,88085249)")
	global:delay(2500)
end

function eleveurs()
	global:delay(2500)
	map:changeMap("zaap(313,240,73400320)")
	global:delay(2500)
end

function frigost()
	global:delay(2500)
	map:changeMap("zaap(303,206,54172969)")
	global:delay(2500)
end

function pandala()
	global:delay(2500)
	map:changeMap("zaap(143,201,207619076)")
	global:delay(2500)
end

function otomai()
	global:delay(2500)
	map:changeMap("zaap(304,204,154642)")
	global:delay(2500)
end

function sortir()
	global:clickPosition(134,368,false)
end

function click()
	global:clickPosition(42,226,false)
end

function changeMapTop()
	global:clickPosition(154,94,false)
end
	
function bank()
	return {
		{map="0,0",custom=astrub},
		{map="5,-18",changeMap="left"},
		{map="191104002",changeMap="289"},
		{map="192415750",custom=hiboux,changeMap="424"},
	}
end

function move()
	if (job:level(26) < 20) then
        ELEMENTS_TO_GATHER = {254}
	return 
	{
		{map = "0,0",custom = astrub},
		{map = "5,-18", changeMap = "bottom", gather = true},
		{map = "5,-17", changeMap = "bottom", gather = true},
		{map = "5,-16", changeMap = "left", gather = true},
		{map = "4,-16", changeMap = "left", gather = true},
		{map = "3,-16", changeMap = "left", gather = true},
		{map = "2,-16", changeMap = "left", gather = true},
		{map = "1,-16", changeMap = "bottom", gather = true},
		{map = "1,-15", changeMap = "right", gather = true},
		{map = "2,-15", changeMap = "right", gather = true},
		{map = "3,-15", changeMap = "right", gather = true},
		{map = "4,-15", changeMap = "right", gather = true},
		{map = "5,-15", changeMap = "right", gather = true},
		{map = "6,-15", changeMap = "top", gather = true},
		{map = "6,-16", changeMap = "right", gather = true},
		{map = "7,-16", changeMap = "right", gather = true},
		{map = "8,-16", changeMap = "right", gather = true},
		{map = "9,-16", changeMap = "bottom", gather = true},
		{map = "9,-15", changeMap = "bottom", gather = true},
		{map = "9,-14", changeMap = "left", gather = true},
		{map = "8,-14", changeMap = "left", gather = true},
		{map = "7,-14", changeMap = "left", gather = true},
		{map = "6,-14", changeMap = "left", gather = true},
		{map = "5,-14", changeMap = "left", gather = true},
		{map = "4,-14", changeMap = "left", gather = true},
		{map = "3,-14", changeMap = "bottom", gather = true},
		{map = "3,-13", changeMap = "right", gather = true},
		{map = "4,-13", changeMap = "right", gather = true},
		{map = "5,-13", changeMap = "right", gather = true},
		{map = "6,-13", changeMap = "right", gather = true},
		{map = "7,-13", changeMap = "right", gather = true},
		{map = "8,-13", changeMap = "right", gather = true},
		{map = "9,-13", changeMap = "right", gather = true},
		{map = "10,-13", changeMap = "right", gather = true},
		{map = "11,-13", changeMap = "bottom", gather = true},
		{map = "11,-12", changeMap = "left", gather = true},
		{map = "10,-12", changeMap = "left", gather = true},
		{map = "8,-12", changeMap = "left", gather = true},
		{map = "9,-12", changeMap = "left", gather = true},
		{map = "7,-12", changeMap = "left", gather = true},
		{map = "5,-12", changeMap = "left", gather = true},
		{map = "6,-12", changeMap = "left", gather = true},
		{map = "4,-12", changeMap = "left", gather = true},
		{map = "3,-12", changeMap = "bottom", gather = true},
		{map = "3,-11", changeMap = "right", gather = true},
		{map = "4,-11", changeMap = "right", gather = true},
		{map = "5,-11", changeMap = "right", gather = true},
		{map = "6,-11", changeMap = "right", gather = true},
		{map = "7,-11", changeMap = "right", gather = true},
		{map = "8,-11", changeMap = "right", gather = true},
		{map = "9,-11", changeMap = "bottom", gather = true},
		{map = "9,-10", changeMap = "left", gather = true},
		{map = "8,-10", changeMap = "left", gather = true},
		{map = "7,-10", changeMap = "left", gather = true},
		{map = "6,-10", changeMap = "left", gather = true},
		{map = "5,-10", changeMap = "left", gather = true},
		{map = "4,-10", changeMap = "left", gather = true},
		{map = "3,-10", changeMap = "bottom", gather = true},
		{map = "3,-9", changeMap = "right", gather = true},
		{map = "4,-9", changeMap = "right", gather = true},
		{map = "5,-9", changeMap = "right", gather = true},
		{map = "6,-9", changeMap = "right", gather = true},
		{map = "7,-9", changeMap = "right", gather = true},
		{map = "8,-9", changeMap = "right", gather = true},	
	}
	elseif (job:level(26) >= 20) and (job:level(26) < 40) then
		ELEMENTS_TO_GATHER = {254,255}
	return {
		{map = "0,0", custom = astrub},
		{map = "5,-18", changeMap = "bottom", gather = true},
		{map = "5,-17", changeMap = "bottom", gather = true},
		{map = "5,-16", changeMap = "left", gather = true},
		{map = "4,-16", changeMap = "left", gather = true},
		{map = "3,-16", changeMap = "left", gather = true},
		{map = "2,-16", changeMap = "bottom", gather = true},
		{map = "2,-15", changeMap = "right", gather = true},
		{map = "3,-15", changeMap = "right", gather = true},
		{map = "4,-15", changeMap = "right", gather = true},
		{map = "5,-15", changeMap = "right", gather = true},
		{map = "6,-15", changeMap = "right", gather = true},
		{map = "7,-15", changeMap = "bottom", gather = true},
		{map = "7,-14", changeMap = "right", gather = true},
		{map = "8,-14", changeMap = "right", gather = true},
		{map = "9,-14", changeMap = "right", gather = true},
		{map = "10,-14", changeMap = "bottom", gather = true},
		{map = "10,-13", changeMap = "left", gather = true},
		{map = "9,-13", changeMap = "left", gather = true},
		{map = "8,-13", changeMap = "left", gather = true},
		{map = "7,-13", changeMap = "left", gather = true},
		{map = "6,-13", changeMap = "left", gather = true},
		{map = "5,-13", changeMap = "left", gather = true},
		{map = "4,-13", changeMap = "left", gather = true},
		{map = "3,-13", changeMap = "bottom", gather = true},
		{map = "3,-12", changeMap = "right", gather = true},
		{map = "4,-12", changeMap = "right", gather = true},
		{map = "5,-12", changeMap = "right", gather = true},
		{map = "6,-12", changeMap = "right", gather = true},
		{map = "7,-12", changeMap = "right", gather = true},
		{map = "8,-12", changeMap = "right", gather = true},
		{map = "9,-12", changeMap = "right", gather = true},
		{map = "10,-12", changeMap = "bottom", gather = true},
		{map = "10,-11", changeMap = "left", gather = true},
		{map = "9,-11", changeMap = "left", gather = true},
		{map = "8,-11", changeMap = "left", gather = true},
		{map = "7,-11", changeMap = "left", gather = true},
		{map = "6,-11", changeMap = "left", gather = true},
		{map = "5,-11", changeMap = "left", gather = true},
		{map = "4,-11", changeMap = "left", gather = true},
		{map = "3,-11", changeMap = "bottom", gather = true},
		{map = "3,-10", changeMap = "right", gather = true},
		{map = "4,-10", changeMap = "right", gather = true},
		{map = "5,-10", changeMap = "right", gather = true},
	}
	elseif (job:level(26) >= 40) and (job:level(26) < 60) then
		ELEMENTS_TO_GATHER = {254,255,67}
	return 
	{	
		{map = "0,0" , custom = astrub },
		{map = "5,-18", changeMap = "left", gather = true},
		{map = "4,-18", changeMap = "top", gather = true},
		{map = "4,-19", changeMap = "top", gather = true},
		{map = "23,-22", changeMap = "top|left", gather = true},
		{map = "4,-20", changeMap = "left", gather = true},
		{map = "3,-20", changeMap = "left", gather = true},
		{map = "2,-20", changeMap = "top", gather = true},
		{map = "2,-21", changeMap = "top", gather = true},
		{map = "2,-22", changeMap = "top", gather = true},
		{map = "2,-23", changeMap = "left", gather = true},
		{map = "1,-23", changeMap = "left", gather = true},
		{map = "0,-23", changeMap = "bottom", gather = true},
		{map = "0,-22", changeMap = "bottom", gather = true},
		{map = "0,-21", changeMap = "bottom", gather = true},
		{map = "0,-20", changeMap = "bottom", gather = true},
		{map = "0,-18", changeMap = "bottom", gather = true},
		{map = "0,-19", changeMap = "bottom", gather = true},
		{map = "0,-17", changeMap = "bottom", gather = true},
		{map = "0,-16", changeMap = "bottom", gather = true},
		{map = "0,-15", changeMap = "left", gather = true},
		{map = "-1,-15", changeMap = "top", gather = true},
		{map = "-1,-16", changeMap = "top", gather = true},
		{map = "-1,-17", changeMap = "top", gather = true},
		{map = "-1,-18", changeMap = "top", gather = true},
		{map = "-1,-19", changeMap = "top", gather = true},
		{map = "-1,-20", changeMap = "top", gather = true},
		{map = "-1,-21", changeMap = "left", gather = true},
		{map = "-2,-21", changeMap = "bottom", gather = true},
		{map = "-2,-20", changeMap = "bottom", gather = true},
		{map = "-2,-19", changeMap = "bottom", gather = true},
		{map = "-2,-18", changeMap = "bottom", gather = true},
		{map = "-2,-17", changeMap = "bottom", gather = true},
		{map = "-2,-16", changeMap = "left", gather = true},
		{map = "-3,-16", changeMap = "top", gather = true},
		{map = "-3,-17", changeMap = "top", gather = true},
		{map = "-3,-18", changeMap = "top", gather = true},
		{map = "-3,-19", changeMap = "top", gather = true},
		{map = "-3,-20", changeMap = "top", gather = true},
		{map = "-3,-21", changeMap = "top", gather = true},
		{map = "-3,-22", changeMap = "top", gather = true},
	}
	elseif (job:level(26) >= 60) and (job:level(26) < 80) then
		ELEMENTS_TO_GATHER = {254,255,67,66}
	return 
	{	
		{map = "0,0" , custom = astrub },
		{map = "5,-18", changeMap = "left", gather = true},
		{map = "4,-18", changeMap = "top", gather = true},
		{map = "4,-19", changeMap = "top", gather = true},
		{map = "4,-20", changeMap = "left", gather = true},
		{map = "3,-20", changeMap = "left", gather = true},
		{map = "2,-20", changeMap = "left", gather = true},
		{map = "1,-20", changeMap = "left", gather = true},
		{map = "0,-20", changeMap = "left", gather = true},
		{map = "-1,-20", changeMap = "bottom", gather = true},
		{map = "-1,-19", changeMap = "left", gather = true},
		{map = "-2,-19", changeMap = "left", gather = true},
		{map = "-3,-19", changeMap = "left", gather = true},
		{map = "-4,-19", changeMap = "left", gather = true},
		{map = "-5,-19", changeMap = "bottom", gather = true},
		{map = "-5,-18", changeMap = "right", gather = true},
		{map = "-4,-18", changeMap = "right", gather = true},
		{map = "-3,-18", changeMap = "right", gather = true},
		{map = "-2,-18", changeMap = "right", gather = true},
		{map = "-1,-18", changeMap = "bottom", gather = true},
		{map = "-1,-17", changeMap = "right", gather = true},
		{map = "0,-17", changeMap = "bottom", gather = true},
		{map = "0,-16", changeMap = "left", gather = true},
		{map = "-1,-16", changeMap = "left", gather = true},
		{map = "-2,-16", changeMap = "left", gather = true},
		{map = "-3,-16", changeMap = "left", gather = true},
		{map = "-4,-16", changeMap = "bottom", gather = true},
		{map = "-4,-15", changeMap = "right", gather = true},
		{map = "-3,-15", changeMap = "right", gather = true},
		{map = "-2,-15", changeMap = "right", gather = true},
		{map = "-1,-15", changeMap = "right", gather = true},
		{map = "0,-15", changeMap = "right", gather = true},
		{map = "2,-15", changeMap = "right", gather = true},
		{map = "1,-15", changeMap = "right", gather = true},
		{map = "3,-15", changeMap = "right", gather = true},
		{map = "4,-15", changeMap = "right", gather = true},
		{map = "5,-15", changeMap = "right", gather = true},
		{map = "6,-15", changeMap = "right", gather = true},
		{map = "7,-15", changeMap = "right", gather = true},
		{map = "8,-15", changeMap = "right", gather = true},
		{map = "9,-15", changeMap = "bottom", gather = true},
		{map = "9,-14", changeMap = "bottom", gather = true},
		{map = "9,-13", changeMap = "left", gather = true},
		{map = "8,-13", changeMap = "left", gather = true},
		{map = "7,-13", changeMap = "left", gather = true},
		{map = "6,-13", changeMap = "left", gather = true},
		{map = "5,-13", changeMap = "left", gather = true},
	}
	elseif (job:level(26) >= 80) and (job:level(26) < 100) then
		ELEMENTS_TO_GATHER = {254,255,67,66,68}
	return 
	{	
		{map = "0,0", custom = eleveurs},
		{map = "-16,1", changeMap = "right", gather = true},
		{map = "-15,1", changeMap = "right", gather = true},
		{map = "-14,1", changeMap = "bottom", gather = true},
		{map = "-14,2", changeMap = "bottom", gather = true},
		{map = "-14,3", changeMap = "left", gather = true},
		{map = "-15,3", changeMap = "top", gather = true},
		{map = "-15,2", changeMap = "left", gather = true},
		{map = "-16,2", changeMap = "left", gather = true},
		{map = "-17,2", changeMap = "left", gather = true},
		{map = "-18,2", changeMap = "bottom", gather = true},
		{map = "-18,3", changeMap = "bottom", gather = true},
		{map = "-18,4", changeMap = "left", gather = true},
		{map = "-19,4", changeMap = "left", gather = true},
		{map = "-20,4", changeMap = "left", gather = true},
		{map = "-21,4", changeMap = "left", gather = true},
		{map = "-22,4", changeMap = "top", gather = true},
		{map = "-22,3", changeMap = "left", gather = true},
		{map = "-23,3", changeMap = "top", gather = true},
		{map = "-23,2", changeMap = "right", gather = true},
		{map = "-22,2", changeMap = "right", gather = true},
		{map = "-21,2", changeMap = "bottom", gather = true},
		{map = "-21,3", changeMap = "right", gather = true},
		{map = "-20,3", changeMap = "right", gather = true},
		{map = "-19,3", changeMap = "top", gather = true},
		{map = "-19,2", changeMap = "left", gather = true},
		{map = "-20,2", changeMap = "top", gather = true},
		{map = "-20,1", changeMap = "right", gather = true},
		{map = "-19,1", changeMap = "top", gather = true},
		{map = "-20,0", changeMap = "left", gather = true},
		{map = "-21,0", changeMap = "bottom", gather = true},
		{map = "-21,1", changeMap = "left", gather = true},
		{map = "-22,1", changeMap = "left", gather = true},
		{map = "-19,0", changeMap = "top", gather = true},
		{map = "-19,-1", changeMap = "left", gather = true},
		{map = "-20,-1", changeMap = "bottom", gather = true},
	}
	elseif (job:level(26) >= 100) and (job:level(26) < 120) then
		ELEMENTS_TO_GATHER = {254,255,67,66,68,61}
	return 
	{	
		{map = "0,0", custom = frigost},
		{map = "-78,-41", changeMap = "left", gather = true},
		{map = "-79,-41", changeMap = "left", gather = true},
		{map = "-80,-41", changeMap = "left", gather = true},
		{map = "-81,-41", changeMap = "left", gather = true},
		{map = "-82,-41", changeMap = "top", gather = true},
		{map = "-82,-42", changeMap = "top", gather = true},
		{map = "-82,-43", changeMap = "right", gather = true},
		{map = "-81,-43", changeMap = "top", gather = true},
		{map = "-81,-44", changeMap = "left", gather = true},
		{map = "-82,-44", changeMap = "left", gather = true},
		{map = "-83,-44", changeMap = "left", gather = true},
		{map = "-84,-44", changeMap = "left", gather = true},
		{map = "-85,-44", changeMap = "top", gather = true},
		{map = "-85,-45", changeMap = "top", gather = true},
		{map = "-85,-46", changeMap = "top", gather = true},
		{map = "-85,-47", changeMap = "right", gather = true},
		{map = "-84,-47", changeMap = "right", gather = true},
		{map = "-83,-47", changeMap = "right", gather = true},
		{map = "-82,-47", changeMap = "top", gather = true},
		{map = "-82,-48", changeMap = "right", gather = true},
		{map = "-81,-48", changeMap = "right", gather = true},
		{map = "-80,-48", changeMap = "right", gather = true},
		{map = "-79,-48", changeMap = "bottom", gather = true},
		{map = "-79,-47", changeMap = "right", gather = true},
		{map = "-78,-47", changeMap = "right", gather = true},
		{map = "-77,-47", changeMap = "right", gather = true},
		{map = "-76,-47", changeMap = "right", gather = true},
		{map = "-75,-47", changeMap = "right", gather = true},
		{map = "-74,-47", changeMap = "right", gather = true},
		{map = "-73,-47", changeMap = "top", gather = true},
		{map = "-73,-48", changeMap = "top", gather = true},
		{map = "-73,-49", changeMap = "top", gather = true},
		{map = "-73,-50", changeMap = "top", gather = true},
		{map = "-73,-51", changeMap = "top", gather = true},
		{map = "-73,-52", changeMap = "top", gather = true},
		{map = "-73,-53", changeMap = "right", gather = true},
		{map = "-72,-53", changeMap = "right", gather = true},
		{map = "-70,-56", changeMap = "right", gather = true},
		{map = "-69,-56", changeMap = "right", gather = true},
		{map = "-68,-56", changeMap = "right", gather = true},
		{map = "-67,-56", changeMap = "top", gather = true},
		{map = "-67,-57", changeMap = "top", gather = true},
		{map = "-67,-58", changeMap = "top", gather = true},
		{map = "-67,-59", changeMap = "right", gather = true},
		{map = "-66,-59", changeMap = "right", gather = true},
		{map = "-65,-59", changeMap = "right", gather = true},
		{map = "-64,-59", changeMap = "right", gather = true},
		{map = "-63,-59", changeMap = "top", gather = true},
		{map = "-63,-60", changeMap = "right", gather = true},
		{map = "-62,-60", changeMap = "right", gather = true},
		{map = "-61,-60", changeMap = "right", gather = true},
		{map = "-60,-60", changeMap = "top", gather = true},
		{map = "-60,-61", changeMap = "top", gather = true},
		{map = "-60,-62", changeMap = "top", gather = true},
		{map = "-60,-63", changeMap = "right", gather = true},
		{map = "-59,-63", changeMap = "top", gather = true},
		{map = "-59,-64", changeMap = "top", gather = true},
		{map = "-59,-65", changeMap = "top", gather = true},
		{map = "-59,-66", changeMap = "right", gather = true},
		{map = "-58,-66", changeMap = "right", gather = true},
		{map = "-57,-66", changeMap = "bottom", gather = true},
		{map = "-57,-65", changeMap = "bottom", gather = true},
		{map = "-57,-64", changeMap = "bottom", gather = true},
		{map = "-57,-63", changeMap = "left", gather = true},
		{map = "-58,-63", changeMap = "bottom", gather = true},
		{map = "-58,-62", changeMap = "bottom", gather = true},
		{map = "-58,-61", changeMap = "bottom", gather = true},
		{map = "-58,-60", changeMap = "right", gather = true},
		{map = "-57,-60", changeMap = "right", gather = true},
		{map = "-56,-60", changeMap = "right", gather = true},
		{map = "-55,-60", changeMap = "bottom", gather = true},
		{map = "-55,-59", changeMap = "left", gather = true},
		{map = "-56,-59", changeMap = "left", gather = true},
		{map = "-57,-59", changeMap = "bottom", gather = true},
		{map = "-57,-58", changeMap = "bottom", gather = true},
		{map = "-57,-57", changeMap = "left", gather = true},
		{map = "-58,-57", changeMap = "bottom", gather = true},
		{map = "-58,-56", changeMap = "left", gather = true},
		{map = "-59,-56", changeMap = "left", gather = true},
		{map = "-60,-56", changeMap = "bottom", gather = true},
		{map = "-60,-55", changeMap = "bottom", gather = true},
		{map = "-60,-54", changeMap = "bottom", gather = true},
		{map = "-60,-53", changeMap = "bottom", gather = true},
		{map = "-60,-52", changeMap = "bottom", gather = true},
		{map = "-60,-51", changeMap = "left", gather = true},
		{map = "-61,-51", changeMap = "bottom", gather = true},
		{map = "-71,-55", changeMap = "top", gather = true},
		{map = "-71,-56", changeMap = "right", gather = true},
		{map = "-71,-54", changeMap = "top", gather = true},
		{map = "-71,-53", changeMap = "top", gather = true},
	}
	elseif (job:level(26) >= 120) and (job:level(26) < 140) then
		ELEMENTS_TO_GATHER = {254,255,67,66,68,61,112}
	return 
	{	
		{map = "0,0", custom = pandala},
		{map = "207619076",custom=sortir},
		{map = "206307842",changeMap="right",gather=true},
		{map = "21,-29",changeMap="right",gather=true},
		{map = "22,-29",changeMap="bottom",gather=true},
		{map = "22,-28",changeMap="right",gather=true},
		{map = "23,-28",changeMap="right",gather=true},
		{map = "24,-28",changeMap="top",gather=true},
		{map = "24,-29",changeMap="right",gather=true},
		{map = "25,-29",changeMap="right",gather=true},
		{map = "26,-29",changeMap="top",gather=true},
		{map = "26,-30",changeMap="left",gather=true},
		{map = "25,-30",changeMap="left",gather=true},
		{map = "24,-30",changeMap="top",gather=true},
		{map = "24,-31",changeMap="right",gather=true},
		{map = "25,-31",changeMap="right",gather=true},
		{map = "26,-31",changeMap="top",gather=true},
		{map = "26,-32",changeMap="left",gather=true},
		{map = "25,-32",changeMap="top",gather=true},
		{map = "25,-33",changeMap="left",gather=true},
		{map = "24,-33",custom=click},
		{map = "23,-33",changeMap="left",gather=true},
		{map = "22,-33",changeMap="top",gather=true},
		{map = "22,-34",changeMap="left",gather=true},
		{map = "21,-34",changeMap="bottom",gather=true},
		{map = "21,-33",changeMap="left",gather=true},
		{map = "20,-33",changeMap="bottom",gather=true},
		{map = "20,-32",changeMap="left",gather=true},
		{map = "19,-32",changeMap="bottom",gather=true},
		{map = "19,-31",changeMap="right",gather=true},
		{map = "20,-31",changeMap="bottom",gather=true},
		{map = "20,-30",changeMap="left",gather=true},
		{map = "19,-30",changeMap="bottom",gather=true},
		{map = "19,-29",changeMap="bottom",gather=true},
		{map = "19,-28",changeMap="right",gather=true},
		{map = "20,-28",changeMap="bottom",gather=true},
		{map = "20,-27",changeMap="bottom",gather=true},
		{map = "20,-26",changeMap="bottom",gather=true},
		{map = "20,-25",changeMap="bottom",gather=true},
		{map = "20,-24",changeMap="left",gather=true},
		{map = "19,-24",changeMap="left",gather=true},
		{map = "18,-24",changeMap="bottom",gather=true},
		{map = "18,-23",changeMap="right",gather=true},
		{map = "19,-23",changeMap="right",gather=true},
		{map = "20,-23",changeMap="bottom",gather=true},
		{map = "20,-22",changeMap="left",gather=true},
		{map = "19,-22",changeMap="bottom",gather=true},
		{map = "19,-21",changeMap="right",gather=true},
		{map = "20,-21",changeMap="bottom",gather=true},
		{map = "20,-20",changeMap="right",gather=true},
		{map = "21,-20",changeMap="top",gather=true},
		{map = "21,-21",changeMap="top",gather=true},
		{map = "21,-22",changeMap="right",gather=true},
		{map = "22,-22",changeMap="top",gather=true},
		{map = "22,-23",custom=changeMapTop,gather=true},
		{map = "22,-24",changeMap="left",gather=true},
		{map = "21,-24",changeMap="top",gather=true},
		{map = "21,-25",changeMap="top",gather=true},
	}
	elseif (job:level(26) >= 140) and (job:level(26) < 160) then
		ELEMENTS_TO_GATHER = {254,255,67,66,68,61,112,256}
	return 
	{	
		{map = "0,0", custom = frigost},
		{map = "-78,-41", changeMap = "right", gather = true},
		{map = "-77,-41", changeMap = "right", gather = true},
		{map = "-76,-41", changeMap = "top", gather = true},
		{map = "-76,-42", changeMap = "top", gather = true},
		{map = "-76,-43", changeMap = "top", gather = true},
		{map = "-76,-44", changeMap = "top", gather = true},
		{map = "-76,-45", changeMap = "top", gather = true},
		{map = "-76,-46", changeMap = "top", gather = true},
		{map = "-76,-47", changeMap = "top", gather = true},
		{map = "-76,-48", changeMap = "top", gather = true},
		{map = "-76,-49", changeMap = "right", gather = true},
		{map = "-75,-49", changeMap = "top", gather = true},
		{map = "-75,-50", changeMap = "right", gather = true},
		{map = "-74,-50", changeMap = "top", gather = true},
		{map = "-74,-51", changeMap = "top", gather = true},
		{map = "-74,-52", changeMap = "top", gather = true},
		{map = "-74,-53", changeMap = "top", gather = true},
		{map = "-74,-54", changeMap = "right", gather = true},
		{map = "-73,-54", changeMap = "bottom", gather = true},
		{map = "-73,-53", changeMap = "right", gather = true},
		{map = "-72,-53", changeMap = "right", gather = true},
		{map = "-71,-53", changeMap = "top", gather = true},
		{map = "-71,-54", changeMap = "top", gather = true},
		{map = "-71,-55", changeMap = "top", gather = true},
		{map = "-71,-56", changeMap = "right", gather = true},
		{map = "-70,-56", changeMap = "right", gather = true},
		{map = "-69,-56", changeMap = "right", gather = true},
		{map = "-68,-56", changeMap = "top", gather = true},
		{map = "-68,-57", changeMap = "top", gather = true},
		{map = "-68,-58", changeMap = "right", gather = true},
		{map = "-67,-58", changeMap = "right", gather = true},
		{map = "-66,-58", changeMap = "right", gather = true},
		{map = "-65,-58", changeMap = "top", gather = true},
		{map = "-65,-59", changeMap = "right", gather = true},
		{map = "-64,-59", changeMap = "top", gather = true},
		{map = "-64,-60", changeMap = "top", gather = true},
		{map = "-64,-61", changeMap = "left", gather = true},
		{map = "-65,-61", changeMap = "top", gather = true},
		{map = "-65,-62", changeMap = "right", gather = true},
		{map = "-64,-62", changeMap = "right", gather = true},
		{map = "-63,-62", changeMap = "right", gather = true},
		{map = "-62,-62", changeMap = "right", gather = true},
		{map = "-60,-62", changeMap = "right", gather = true},
		{map = "-61,-62", changeMap = "right", gather = true},
		{map = "-59,-62", changeMap = "top", gather = true},
		{map = "-59,-63", changeMap = "right", gather = true},
		{map = "-58,-63", changeMap = "right", gather = true},
		{map = "-57,-63", changeMap = "bottom", gather = true},
		{map = "-57,-62", changeMap = "bottom", gather = true},
		{map = "-57,-61", changeMap = "bottom", gather = true},
		{map = "-57,-60", changeMap = "bottom", gather = true},
		{map = "-57,-59", changeMap = "right", gather = true},
		{map = "-56,-59", changeMap = "bottom", gather = true},
		{map = "-56,-58", changeMap = "bottom", gather = true},
		{map = "-56,-57", changeMap = "left", gather = true},
		{map = "-57,-57", changeMap = "bottom", gather = true},
		{map = "-57,-56", changeMap = "left", gather = true},
		{map = "-58,-56", changeMap = "bottom", gather = true},
		{map = "-58,-55", changeMap = "left", gather = true},
		{map = "-59,-55", changeMap = "bottom", gather = true},
		{map = "-59,-53", changeMap = "bottom", gather = true},
		{map = "-59,-52", changeMap = "left", gather = true},
		{map = "-60,-52", changeMap = "left", gather = true},
		{map = "-61,-52", changeMap = "left", gather = true},
		{map = "-62,-52", changeMap = "left", gather = true},
		{map = "-64,-52", changeMap = "left", gather = true},
		{map = "-63,-52", changeMap = "left", gather = true},
		{map = "-65,-52", changeMap = "left", gather = true},
		{map = "-66,-52", changeMap = "bottom", gather = true},
		{map = "-66,-51", changeMap = "bottom", gather = true},
		{map = "-66,-50", changeMap = "bottom", gather = true},
		{map = "-66,-49", changeMap = "bottom", gather = true},
		{map = "-66,-48", changeMap = "bottom", gather = true},
		{map = "-66,-47", changeMap = "left", gather = true},
		{map = "-67,-47", changeMap = "left", gather = true},
		{map = "-68,-47", changeMap = "left", gather = true},
		{map = "-59,-54", changeMap = "right", gather = true},
		{map = "-58,-54", changeMap = "bottom", gather = true},
		{map = "-58,-53", changeMap = "left", gather = true},
	}
	elseif (job:level(26) >= 160) and (job:level(26) < 180) then
		ELEMENTS_TO_GATHER = {254,255,67,66,68,61,112,256,257}
	return 
	{	
		{map = "0,0", custom = otomai},
		{map = "-46,18", changeMap = "bottom", gather = true},
		{map = "-46,19", changeMap = "right", gather = true},
		{map = "-45,19", changeMap = "top", gather = true},
		{map = "-45,18", changeMap = "top", gather = true},
		{map = "-45,17", changeMap = "top", gather = true},
		{map = "-45,16", changeMap = "top", gather = true},
		{map = "-45,15", changeMap = "left", gather = true},
		{map = "-46,15", changeMap = "left", gather = true},
		{map = "-47,15", changeMap = "bottom", gather = true},
		{map = "-47,16", changeMap = "bottom", gather = true},
		{map = "-47,17", changeMap = "bottom", gather = true},
		{map = "-47,18", changeMap = "bottom", gather = true},
		{map = "-47,19", changeMap = "left", gather = true},
		{map = "-48,19", changeMap = "top", gather = true},
		{map = "-48,18", changeMap = "top", gather = true},
		{map = "-48,17", changeMap = "top", gather = true},
		{map = "-48,16", changeMap = "top", gather = true},
		{map = "-48,15", changeMap = "top", gather = true},
		{map = "-48,14", changeMap = "top", gather = true},
		{map = "-48,13", changeMap = "top", gather = true},
		{map = "-48,12", changeMap = "left", gather = true},
		{map = "-49,12", changeMap = "bottom", gather = true},
		{map = "-49,13", changeMap = "bottom", gather = true},
		{map = "-49,14", changeMap = "bottom", gather = true},
		{map = "-49,15", changeMap = "bottom", gather = true},
		{map = "-49,16", changeMap = "bottom", gather = true},
		{map = "-49,18", changeMap = "bottom", gather = true},
		{map = "-49,19", changeMap = "bottom", gather = true},
		{map = "-49,17", changeMap = "bottom", gather = true},
		{map = "-49,20", changeMap = "bottom", gather = true},
		{map = "-49,21", changeMap = "left", gather = true},
		{map = "-50,21", changeMap = "left", gather = true},
		{map = "-51,21", changeMap = "top", gather = true},
		{map = "-51,20", changeMap = "top", gather = true},
		{map = "-51,19", changeMap = "top", gather = true},
		{map = "-51,18", changeMap = "top", gather = true},
		{map = "-51,17", changeMap = "top", gather = true},
		{map = "-51,16", changeMap = "right", gather = true},
		{map = "-50,16", changeMap = "top", gather = true},
		{map = "-50,15", changeMap = "top", gather = true},
		{map = "-50,14", changeMap = "left", gather = true},
		{map = "-51,14", changeMap = "bottom", gather = true},
		{map = "-51,15", changeMap = "left", gather = true},
		{map = "-52,15", changeMap = "left", gather = true},
		{map = "-53,15", changeMap = "left", gather = true},
		{map = "-54,15", changeMap = "left", gather = true},
		{map = "-55,15", changeMap = "bottom", gather = true},
		{map = "-55,16", changeMap = "bottom", gather = true},
		{map = "-55,17", changeMap = "left", gather = true},
		{map = "-56,17", changeMap = "bottom", gather = true},
		{map = "-56,18", changeMap = "bottom", gather = true},
		{map = "-56,19", changeMap = "right", gather = true},
		{map = "-55,19", changeMap = "top", gather = true},
		{map = "-55,18", changeMap = "right", gather = true},
		{map = "-54,18", changeMap = "right", gather = true},
		{map = "-53,18", changeMap = "right", gather = true},
		{map = "-52,18", changeMap = "bottom", gather = true},
		{map = "-52,19", changeMap = "left", gather = true},
		{map = "-53,19", changeMap = "left", gather = true},
		{map = "-54,19", changeMap = "bottom", gather = true},
		{map = "-54,20", changeMap = "left", gather = true},
		{map = "-55,20", changeMap = "bottom", gather = true},
		{map = "-54,21", changeMap = "right", gather = true},
		{map = "-55,21", changeMap = "right", gather = true},
		{map = "-53,21", changeMap = "top", gather = true},
		{map = "-53,20", changeMap = "right", gather = true},
	}
	elseif (job:level(26) >= 180) and (job:level(26) < 200) then
		ELEMENTS_TO_GATHER = {254,255,67,66,68,61,112,256,257,258}
	return 
	{	
		{map = "0,0",custom = rivage},
		{map = "10,22", changeMap = "right", gather = true},
		{map = "11,22", changeMap = "right", gather = true},
		{map = "12,22", changeMap = "right", gather = true},
		{map = "13,22", changeMap = "top", gather = true},
		{map = "13,21", changeMap = "top", gather = true},
		{map = "13,20", changeMap = "top", gather = true},
		{map = "13,19", changeMap = "top", gather = true},
		{map = "13,18", changeMap = "top", gather = true},
		{map = "13,17", changeMap = "top", gather = true},
		{map = "13,16", changeMap = "left", gather = true},
		{map = "12,16", changeMap = "left", gather = true},
		{map = "11,16", changeMap = "left", gather = true},
		{map = "10,16", changeMap = "bottom", gather = true},
		{map = "10,17", changeMap = "left", gather = true},
		{map = "9,17", changeMap = "left", gather = true},
		{map = "8,17", changeMap = "top", gather = true},
		{map = "8,16", changeMap = "right", gather = true},
		{map = "9,16", changeMap = "top", gather = true},
		{map = "9,15", changeMap = "top", gather = true},
		{map = "9,14", changeMap = "right", gather = true},
		{map = "10,14", changeMap = "bottom", gather = true},
		{map = "10,15", changeMap = "right", gather = true},
	}
end
end