MAX_PODS = 95

function astrub()
    global:delay(2500)
    map:changeMap("zaap(125,196,191105026)")
    global:delay(2500)
end

function scarafeuille()
    global:delay(2500)
    map:changeMap("zaap(110,199,88212481)")
    global:delay(2500)
end

function craqueleur()
    global:delay(2500)
    map:changeMap("zaap(110,199,185860609)")
    global:delay(2500)
end

function porkass()
    global:delay(2500)
    map:changeMap("zaap(110,199,84806401)")
    global:delay(2500)
end

function roulottes()
    global:delay(2500)
    map:changeMap("zaap(110,199,171967506)")
    global:delay(2500)
end

function otomai()
    global:delay(2500)
    map:changeMap("zaap(110,199,154642)")
    global:delay(2500)
end

function pandala()
    global:delay(1000)
    map:changeMap("zaap(143,201,207619076)")
    global:delay(1000)
end

function plainerocheuse()
    global:delay(2500)
    map:changeMap("zaap(110,199,147590153)")
    global:delay(2500)
end

function eleveurs()
    global:delay(2500)
    map:changeMap("zaap(125,196,73400320)")
    global:delay(2500)
end

function monter()
    global:delay(2500)
    global:clickPosition(86, 9)
end

function descendre()
    global:delay(2500)
    global:clickPosition(524, 463)
end

function enterHavenbag()
	global:delay(2500)
    global:sendKey(72)
    global:delay(2500)
end

function move()
    if (job:level(2) < 20) then
        ELEMENTS_TO_GATHER = {1}
        return {
           {map = "0,0",custom = astrub},
		{map = "5,-18", changeMap = "bottom", gather = true},
		{map = "5,-17", changeMap = "bottom", gather = true},
		{map = "5,-16", changeMap = "bottom", gather = true},
		{map = "5,-15", changeMap = "left", gather = true},
		{map = "4,-15", changeMap = "left", gather = true},
		{map = "3,-15", changeMap = "left", gather = true},
		{map = "2,-15", changeMap = "top", gather = true},
		{map = "2,-16", changeMap = "top", gather = true},
		{map = "2,-17", changeMap = "top", gather = true},
		{map = "2,-18", changeMap = "top", gather = true},
		{map = "2,-19", changeMap = "top", gather = true},
		{map = "2,-20", changeMap = "top", gather = true},
		{map = "2,-21", changeMap = "top", gather = true},
		{map = "2,-22", changeMap = "top", gather = true},
		{map = "2,-23", changeMap = "top", gather = true},
		{map = "2,-24", changeMap = "top", gather = true},
		{map = "2,-25", changeMap = "top", gather = true},
		{map = "2,-26", changeMap = "top", gather = true},
		{map = "2,-27", changeMap = "top", gather = true},
		{map = "2,-28", changeMap = "left", gather = true},
		{map = "1,-28", changeMap = "bottom", gather = true},
		{map = "1,-27", changeMap = "bottom", gather = true},
		{map = "1,-26", changeMap = "bottom", gather = true},
		{map = "1,-25", changeMap = "bottom", gather = true},
		{map = "1,-24", changeMap = "bottom", gather = true},
		{map = "1,-23", changeMap = "bottom", gather = true},
		{map = "1,-22", changeMap = "bottom", gather = true},
		{map = "1,-21", changeMap = "bottom", gather = true},
		{map = "1,-20", changeMap = "bottom", gather = true},
		{map = "1,-19", changeMap = "bottom", gather = true},
		{map = "1,-18", changeMap = "bottom", gather = true},
		{map = "1,-17", changeMap = "bottom", gather = true},
		{map = "1,-16", changeMap = "bottom", gather = true},
		{map = "1,-15", changeMap = "bottom", gather = true},
		{map = "1,-14", changeMap = "left", gather = true},
		{map = "0,-14", changeMap = "top", gather = true},
		{map = "0,-15", changeMap = "top", gather = true},
		{map = "0,-16", changeMap = "top", gather = true},
		{map = "0,-17", changeMap = "top", gather = true},
		{map = "0,-18", changeMap = "top", gather = true},
		{map = "0,-19", changeMap = "top", gather = true},
		{map = "0,-20", changeMap = "top", gather = true},
		{map = "0,-21", changeMap = "top", gather = true},
		{map = "0,-22", changeMap = "top", gather = true},
		{map = "0,-23", changeMap = "top", gather = true},
		{map = "0,-24", changeMap = "top", gather = true},
		{map = "0,-25", changeMap = "top", gather = true},
		{map = "0,-26", changeMap = "top", gather = true},
		{map = "0,-27", changeMap = "top", gather = true},
		{map = "0,-28", changeMap = "left", gather = true},
		{map = "-1,-28", changeMap = "bottom", gather = true},
		{map = "-1,-27", changeMap = "bottom", gather = true},
		{map = "-1,-26", changeMap = "bottom", gather = true},
		{map = "-1,-25", changeMap = "bottom", gather = true},
		{map = "-1,-24", changeMap = "bottom", gather = true},
		{map = "-1,-23", changeMap = "bottom", gather = true},
		{map = "-1,-22", changeMap = "bottom", gather = true},
		{map = "-1,-20", changeMap = "bottom", gather = true},
		{map = "-1,-21", changeMap = "bottom", gather = true},
		{map = "-1,-19", changeMap = "bottom", gather = true},
		{map = "-1,-18", changeMap = "bottom", gather = true},
		{map = "-1,-17", changeMap = "bottom", gather = true},
		{map = "-1,-16", changeMap = "bottom", gather = true},
		{map = "-1,-15", changeMap = "bottom", gather = true},
		{map = "-1,-14", changeMap = "left", gather = true},
		{map = "-2,-14", changeMap = "top", gather = true},
		{map = "-2,-15", changeMap = "top", gather = true},
		{map = "-2,-16", changeMap = "top", gather = true},
		{map = "-2,-17", changeMap = "top", gather = true},
		{map = "-2,-18", changeMap = "top", gather = true},
		{map = "-2,-19", changeMap = "top", gather = true},
		{map = "-2,-20", changeMap = "top", gather = true},
		{map = "-2,-21", changeMap = "top", gather = true},
		{map = "-2,-22", changeMap = "top", gather = true},
		{map = "-2,-23", changeMap = "top", gather = true},
		{map = "-2,-24", changeMap = "top", gather = true},
		{map = "-2,-25", changeMap = "top", gather = true},
		{map = "-2,-26", changeMap = "top", gather = true},
		{map = "-2,-27", changeMap = "top", gather = true},
		{map = "-2,-28", changeMap = "top", gather = true},
		{map = "-2,-29", changeMap = "left", gather = true},
		{map = "-3,-29", changeMap = "bottom", gather = true},
		{map = "-3,-28", changeMap = "bottom", gather = true},
		{map = "-3,-27", changeMap = "bottom", gather = true},
		{map = "-3,-26", changeMap = "bottom", gather = true},
		{map = "-3,-25", changeMap = "bottom", gather = true},
		{map = "-3,-24", changeMap = "bottom", gather = true},
		{map = "-3,-23", changeMap = "bottom", gather = true},
		{map = "-3,-22", changeMap = "bottom", gather = true},
		{map = "-3,-21", changeMap = "bottom", gather = true},
		{map = "-3,-20", changeMap = "bottom", gather = true},
		{map = "-3,-19", changeMap = "bottom", gather = true},
		{map = "-3,-18", changeMap = "bottom", gather = true},
		{map = "-3,-17", changeMap = "bottom", gather = true},
		{map = "-3,-16", changeMap = "bottom", gather = true},
		{map = "-3,-15", changeMap = "bottom", gather = true},
		{map = "-3,-14", changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 20) and (job:level(2) < 40) then
        ELEMENTS_TO_GATHER = {1, 33}
        return {
            {map = "0,0",custom = astrub},
		{map = "5,-18", changeMap = "bottom", gather = true},
		{map = "5,-17", changeMap = "bottom", gather = true},
		{map = "5,-16", changeMap = "bottom", gather = true},
		{map = "5,-15", changeMap = "left", gather = true},
		{map = "4,-15", changeMap = "left", gather = true},
		{map = "3,-15", changeMap = "left", gather = true},
		{map = "2,-15", changeMap = "top", gather = true},
		{map = "2,-16", changeMap = "top", gather = true},
		{map = "2,-17", changeMap = "top", gather = true},
		{map = "2,-18", changeMap = "top", gather = true},
		{map = "2,-19", changeMap = "top", gather = true},
		{map = "2,-20", changeMap = "top", gather = true},
		{map = "2,-21", changeMap = "top", gather = true},
		{map = "2,-22", changeMap = "top", gather = true},
		{map = "2,-23", changeMap = "top", gather = true},
		{map = "2,-24", changeMap = "top", gather = true},
		{map = "2,-25", changeMap = "top", gather = true},
		{map = "2,-26", changeMap = "top", gather = true},
		{map = "2,-27", changeMap = "top", gather = true},
		{map = "2,-28", changeMap = "left", gather = true},
		{map = "1,-28", changeMap = "bottom", gather = true},
		{map = "1,-27", changeMap = "bottom", gather = true},
		{map = "1,-26", changeMap = "bottom", gather = true},
		{map = "1,-25", changeMap = "bottom", gather = true},
		{map = "1,-24", changeMap = "bottom", gather = true},
		{map = "1,-23", changeMap = "bottom", gather = true},
		{map = "1,-22", changeMap = "bottom", gather = true},
		{map = "1,-21", changeMap = "bottom", gather = true},
		{map = "1,-20", changeMap = "bottom", gather = true},
		{map = "1,-19", changeMap = "bottom", gather = true},
		{map = "1,-18", changeMap = "bottom", gather = true},
		{map = "1,-17", changeMap = "bottom", gather = true},
		{map = "1,-16", changeMap = "bottom", gather = true},
		{map = "1,-15", changeMap = "bottom", gather = true},
		{map = "1,-14", changeMap = "left", gather = true},
		{map = "0,-14", changeMap = "top", gather = true},
		{map = "0,-15", changeMap = "top", gather = true},
		{map = "0,-16", changeMap = "top", gather = true},
		{map = "0,-17", changeMap = "top", gather = true},
		{map = "0,-18", changeMap = "top", gather = true},
		{map = "0,-19", changeMap = "top", gather = true},
		{map = "0,-20", changeMap = "top", gather = true},
		{map = "0,-21", changeMap = "top", gather = true},
		{map = "0,-22", changeMap = "top", gather = true},
		{map = "0,-23", changeMap = "top", gather = true},
		{map = "0,-24", changeMap = "top", gather = true},
		{map = "0,-25", changeMap = "top", gather = true},
		{map = "0,-26", changeMap = "top", gather = true},
		{map = "0,-27", changeMap = "top", gather = true},
		{map = "0,-28", changeMap = "left", gather = true},
		{map = "-1,-28", changeMap = "bottom", gather = true},
		{map = "-1,-27", changeMap = "bottom", gather = true},
		{map = "-1,-26", changeMap = "bottom", gather = true},
		{map = "-1,-25", changeMap = "bottom", gather = true},
		{map = "-1,-24", changeMap = "bottom", gather = true},
		{map = "-1,-23", changeMap = "bottom", gather = true},
		{map = "-1,-22", changeMap = "bottom", gather = true},
		{map = "-1,-20", changeMap = "bottom", gather = true},
		{map = "-1,-21", changeMap = "bottom", gather = true},
		{map = "-1,-19", changeMap = "bottom", gather = true},
		{map = "-1,-18", changeMap = "bottom", gather = true},
		{map = "-1,-17", changeMap = "bottom", gather = true},
		{map = "-1,-16", changeMap = "bottom", gather = true},
		{map = "-1,-15", changeMap = "bottom", gather = true},
		{map = "-1,-14", changeMap = "left", gather = true},
		{map = "-2,-14", changeMap = "top", gather = true},
		{map = "-2,-15", changeMap = "top", gather = true},
		{map = "-2,-16", changeMap = "top", gather = true},
		{map = "-2,-17", changeMap = "top", gather = true},
		{map = "-2,-18", changeMap = "top", gather = true},
		{map = "-2,-19", changeMap = "top", gather = true},
		{map = "-2,-20", changeMap = "top", gather = true},
		{map = "-2,-21", changeMap = "top", gather = true},
		{map = "-2,-22", changeMap = "top", gather = true},
		{map = "-2,-23", changeMap = "top", gather = true},
		{map = "-2,-24", changeMap = "top", gather = true},
		{map = "-2,-25", changeMap = "top", gather = true},
		{map = "-2,-26", changeMap = "top", gather = true},
		{map = "-2,-27", changeMap = "top", gather = true},
		{map = "-2,-28", changeMap = "top", gather = true},
		{map = "-2,-29", changeMap = "left", gather = true},
		{map = "-3,-29", changeMap = "bottom", gather = true},
		{map = "-3,-28", changeMap = "bottom", gather = true},
		{map = "-3,-27", changeMap = "bottom", gather = true},
		{map = "-3,-26", changeMap = "bottom", gather = true},
		{map = "-3,-25", changeMap = "bottom", gather = true},
		{map = "-3,-24", changeMap = "bottom", gather = true},
		{map = "-3,-23", changeMap = "bottom", gather = true},
		{map = "-3,-22", changeMap = "bottom", gather = true},
		{map = "-3,-21", changeMap = "bottom", gather = true},
		{map = "-3,-20", changeMap = "bottom", gather = true},
		{map = "-3,-19", changeMap = "bottom", gather = true},
		{map = "-3,-18", changeMap = "bottom", gather = true},
		{map = "-3,-17", changeMap = "bottom", gather = true},
		{map = "-3,-16", changeMap = "bottom", gather = true},
		{map = "-3,-15", changeMap = "bottom", gather = true},
		{map = "-3,-14", changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 40) and (job:level(2) < 60) then
        ELEMENTS_TO_GATHER = {1, 33, 34}
        return {
            {map = "0,0",custom = astrub},
		{map = "5,-18", changeMap = "top", gather = true},
		{map = "4,-19", changeMap = "top", gather = true},
		{map = "4,-20", changeMap = "right", gather = true},
		{map = "5,-20", changeMap = "top", gather = true},
		{map = "5,-21", changeMap = "top", gather = true},
		{map = "5,-22", changeMap = "top", gather = true},
		{map = "5,-23", changeMap = "top", gather = true},
		{map = "5,-24", changeMap = "left", gather = true},
		{map = "4,-24", changeMap = "left", gather = true},
		{map = "3,-24", changeMap = "left", gather = true},
		{map = "2,-24", changeMap = "top", gather = true},
		{map = "2,-25", changeMap = "top", gather = true},
		{map = "2,-26", changeMap = "top", gather = true},
		{map = "2,-27", changeMap = "left", gather = true},
		{map = "1,-27", changeMap = "bottom", gather = true},
		{map = "1,-26", changeMap = "bottom", gather = true},
		{map = "1,-25", changeMap = "bottom", gather = true},
		{map = "1,-24", changeMap = "left", gather = true},
		{map = "0,-24", changeMap = "left", gather = true},
		{map = "-1,-24", changeMap = "top", gather = true},
		{map = "-1,-25", changeMap = "top", gather = true},
		{map = "-1,-26", changeMap = "top", gather = true},
		{map = "-1,-27", changeMap = "top", gather = true},
		{map = "-1,-28", changeMap = "left", gather = true},
		{map = "-2,-28", changeMap = "bottom", gather = true},
		{map = "-2,-27", changeMap = "bottom", gather = true},
		{map = "-2,-26", changeMap = "bottom", gather = true},
		{map = "-2,-25", changeMap = "bottom", gather = true},
		{map = "-2,-24", changeMap = "bottom", gather = true},
		{map = "-2,-23", changeMap = "bottom", gather = true},
		{map = "-3,-22", changeMap = "bottom", gather = true},
		{map = "-3,-20", changeMap = "bottom", gather = true},
		{map = "-3,-21", changeMap = "bottom", gather = true},
		{map = "-3,-19", changeMap = "bottom", gather = true},
		{map = "-3,-18", changeMap = "right", gather = true},
		{map = "-2,-22", changeMap = "left", gather = true},
		{map = "-2,-18", changeMap = "bottom", gather = true},
		{map = "-2,-17", changeMap = "right", gather = true},
		{map = "-1,-17", changeMap = "bottom", gather = true},
		{map = "-1,-16", changeMap = "left", gather = true},
		{map = "-2,-16", changeMap = "left", gather = true},
		{map = "-3,-16", changeMap = "bottom", gather = true},
		{map = "-3,-15", changeMap = "right", gather = true},
		{map = "-2,-15", changeMap = "right", gather = true},
		{map = "-1,-15", changeMap = "right", gather = true},
		{map = "0,-15", changeMap = "right", gather = true},
		{map = "1,-14", changeMap = "right", gather = true},
		{map = "2,-14", changeMap = "right", gather = true},
		{map = "3,-14", changeMap = "right", gather = true},
		{map = "4,-14", changeMap = "right", gather = true},
		{map = "4,-15", changeMap = "top", gather = true},
		{map = "1,-15", changeMap = "bottom", gather = true},
		{map = "5,-19", changeMap = "left", gather = true},
		{map = "4,-16", changeMap = "left", gather = true},
		{map = "3,-16", changeMap = "left", gather = true},
		{map = "2,-16", changeMap = "left", gather = true},
		{map = "1,-16", changeMap = "top", gather = true},
		{map = "1,-17", changeMap = "top", gather = true},
		{map = "1,-18", changeMap = "top", gather = true},
		{map = "1,-19", changeMap = "right", gather = true},
		{map = "2,-19", changeMap = "bottom", gather = true},
		{map = "2,-18", changeMap = "right", gather = true},
		{map = "3,-18", changeMap = "bottom", gather = true},
		{map = "3,-17", changeMap = "right", gather = true},
		{map = "4,-17", changeMap = "top", gather = true},
		{map = "4,-18", changeMap = "right", gather = true},
        }
    elseif (job:level(2) >= 60) and (job:level(2) < 70) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8}
        return {
            {map = "0,0",custom = plainerocheuse},
		{map = "-16,-46", changeMap = "right", gather = true},
		{map = "-17,-46", changeMap = "right", gather = true},
		{map = "-17,-47", changeMap = "bottom", gather = true},
		{map = "-15,-46", changeMap = "top", gather = true},
		{map = "-15,-47", changeMap = "top", gather = true},
		{map = "-15,-48", changeMap = "top", gather = true},
		{map = "-15,-49", changeMap = "top", gather = true},
		{map = "-15,-50", changeMap = "top", gather = true},
		{map = "-15,-51", changeMap = "top", gather = true},
		{map = "-15,-52", changeMap = "top", gather = true},
		{map = "-15,-53", changeMap = "top", gather = true},
		{map = "-15,-54", changeMap = "top", gather = true},
		{map = "-15,-55", changeMap = "top", gather = true},
		{map = "-15,-56", changeMap = "top", gather = true},
		{map = "-15,-57", changeMap = "top", gather = true},
		{map = "-15,-58", changeMap = "top", gather = true},
		{map = "-15,-59", changeMap = "right", gather = true},
		{map = "-14,-59", changeMap = "bottom", gather = true},
		{map = "-14,-58", changeMap = "bottom", gather = true},
		{map = "-14,-57", changeMap = "bottom", gather = true},
		{map = "-14,-56", changeMap = "bottom", gather = true},
		{map = "-14,-55", changeMap = "bottom", gather = true},
		{map = "-14,-54", changeMap = "right", gather = true},
		{map = "-13,-55", changeMap = "bottom", gather = true},
		{map = "-13,-54", changeMap = "bottom", gather = true},
		{map = "-13,-53", changeMap = "left", gather = true},
		{map = "-14,-53", changeMap = "bottom", gather = true},
		{map = "-14,-52", changeMap = "bottom", gather = true},
		{map = "-14,-51", changeMap = "bottom", gather = true},
		{map = "-14,-50", changeMap = "bottom", gather = true},
		{map = "-14,-48", changeMap = "bottom", gather = true},
		{map = "-14,-49", changeMap = "bottom", gather = true},
		{map = "-14,-47", changeMap = "right", gather = true},
		{map = "-13,-47", changeMap = "top", gather = true},
		{map = "-13,-48", changeMap = "top", gather = true},
		{map = "-13,-49", changeMap = "top", gather = true},
		{map = "-13,-50", changeMap = "top", gather = true},
		{map = "-13,-51", changeMap = "top", gather = true},
		{map = "-13,-52", changeMap = "right", gather = true},
		{map = "-12,-52", changeMap = "top", gather = true},
		{map = "-12,-53", changeMap = "top", gather = true},
		{map = "-12,-54", changeMap = "top", gather = true},
		{map = "-12,-55", changeMap = "top", gather = true},
		{map = "-12,-56", changeMap = "right", gather = true},
		{map = "-11,-59", changeMap = "right", gather = true},
		{map = "-10,-59", changeMap = "bottom", gather = true},
		{map = "-10,-58", changeMap = "bottom", gather = true},
		{map = "-10,-57", changeMap = "bottom", gather = true},
		{map = "-10,-56", changeMap = "bottom", gather = true},
		{map = "-11,-56", changeMap = "top", gather = true},
		{map = "-11,-55", changeMap = "bottom", gather = true},
		{map = "-11,-54", changeMap = "bottom", gather = true},
		{map = "-11,-53", changeMap = "right", gather = true},
		{map = "-10,-53", changeMap = "bottom", gather = true},
		{map = "-10,-52", changeMap = "left", gather = true},
		{map = "-11,-52", changeMap = "bottom", gather = true},
		{map = "-11,-51", changeMap = "left", gather = true},
		{map = "-12,-51", changeMap = "bottom", gather = true},
		{map = "-12,-50", changeMap = "bottom", gather = true},
		{map = "-12,-49", changeMap = "right", gather = true},
		{map = "-11,-49", changeMap = "right", gather = true},
		{map = "-10,-49", changeMap = "right", gather = true},
		{map = "-9,-49", changeMap = "bottom", gather = true},
		{map = "-9,-48", changeMap = "right", gather = true},
		{map = "-7,-48", changeMap = "right", gather = true},
		{map = "-6,-48", changeMap = "bottom", gather = true},
		{map = "-6,-47", changeMap = "bottom", gather = true},
		{map = "-6,-46", changeMap = "bottom", gather = true},
		{map = "-6,-45", changeMap = "left", gather = true},
		{map = "-7,-45", changeMap = "top", gather = true},
		{map = "-7,-46", changeMap = "top", gather = true},
		{map = "-7,-47", changeMap = "left", gather = true},
		{map = "-8,-47", changeMap = "left", gather = true},
		{map = "-9,-47", changeMap = "left", gather = true},
		{map = "-8,-48", changeMap = "right", gather = true},
		{map = "-11,-57", changeMap = "top", gather = true},
		{map = "-11,-58", changeMap = "top", gather = true},
		{map = "-10,-55", changeMap = "left", gather = true},
        }
    elseif (job:level(2) >= 70) and (job:level(2) < 80) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98}
        return {
            {map = "0,0",custom = porkass},
		{map = "-5,-23", changeMap = "left", gather = true},
		{map = "-6,-23", changeMap = "bottom", gather = true},
		{map = "-6,-22", changeMap = "bottom", gather = true},
		{map = "-6,-21", changeMap = "bottom", gather = true},
		{map = "-6,-20", changeMap = "bottom", gather = true},
		{map = "-6,-19", changeMap = "left", gather = true},
		{map = "-7,-19", changeMap = "top", gather = true},
		{map = "-7,-20", changeMap = "top", gather = true},
		{map = "-7,-21", changeMap = "top", gather = true},
		{map = "-7,-22", changeMap = "top", gather = true},
		{map = "-7,-23", changeMap = "top", gather = true},
		{map = "-7,-24", changeMap = "top", gather = true},
		{map = "-7,-25", changeMap = "top", gather = true},
		{map = "-7,-26", changeMap = "top", gather = true},
		{map = "-7,-27", changeMap = "top", gather = true},
		{map = "-7,-28", changeMap = "top", gather = true},
		{map = "-7,-29", changeMap = "top", gather = true},
		{map = "-7,-30", changeMap = "right", gather = true},
		{map = "-6,-30", changeMap = "top", gather = true},
		{map = "-6,-31", changeMap = "top", gather = true},
		{map = "-6,-32", changeMap = "top", gather = true},
		{map = "-6,-33", changeMap = "top", gather = true},
		{map = "-6,-34", changeMap = "top", gather = true},
		{map = "-6,-35", changeMap = "left", gather = true},
		{map = "-7,-35", changeMap = "left", gather = true},
		{map = "-8,-36", changeMap = "left", gather = true},
		{map = "-8,-35", changeMap = "top", gather = true},
		{map = "-9,-36", changeMap = "left", gather = true},
		{map = "-10,-36", changeMap = "left", gather = true},
		{map = "-11,-36", changeMap = "left", gather = true},
		{map = "-12,-36", changeMap = "left", gather = true},
		{map = "-13,-36", changeMap = "left", gather = true},
		{map = "-14,-36", changeMap = "bottom", gather = true},
		{map = "-14,-35", changeMap = "right", gather = true},
		{map = "-13,-35", changeMap = "right", gather = true},
		{map = "-12,-35", changeMap = "bottom", gather = true},
		{map = "-12,-34", changeMap = "bottom", gather = true},
		{map = "-12,-33", changeMap = "right", gather = true},
		{map = "-11,-33", changeMap = "right", gather = true},
		{map = "-10,-34", changeMap = "right", gather = true},
		{map = "-9,-33", changeMap = "right", gather = true},
		{map = "-10,-33", changeMap = "top", gather = true},
		{map = "-9,-34", changeMap = "bottom", gather = true},
		{map = "-8,-33", changeMap = "bottom", gather = true},
		{map = "-8,-32", changeMap = "bottom", gather = true},
		{map = "-8,-31", changeMap = "bottom", gather = true},
		{map = "-8,-30", changeMap = "bottom", gather = true},
		{map = "-8,-29", changeMap = "bottom", gather = true},
		{map = "-8,-28", changeMap = "bottom", gather = true},
		{map = "-8,-27", changeMap = "bottom", gather = true},
		{map = "-8,-26", changeMap = "bottom", gather = true},
		{map = "-8,-25", changeMap = "bottom", gather = true},
		{map = "-8,-24", changeMap = "bottom", gather = true},
		{map = "-8,-23", changeMap = "bottom", gather = true},
		{map = "-8,-22", changeMap = "bottom", gather = true},
		{map = "-8,-21", changeMap = "bottom", gather = true},
		{map = "-8,-20", changeMap = "bottom", gather = true},
		{map = "-8,-19", changeMap = "right", gather = true},
        }
    elseif (job:level(2) >= 80) and (job:level(2) < 90) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31}
        return {
            {map = "0,0",custom = plainerocheuse},
		{map = "-16,-46", changeMap = "bottom", gather = true},
		{map = "-17,-46", changeMap = "right", gather = true},
		{map = "-17,-47", changeMap = "bottom", gather = true},
		{map = "-15,-46", changeMap = "top", gather = true},
		{map = "-15,-47", changeMap = "top", gather = true},
		{map = "-15,-48", changeMap = "top", gather = true},
		{map = "-15,-49", changeMap = "top", gather = true},
		{map = "-15,-50", changeMap = "top", gather = true},
		{map = "-15,-51", changeMap = "top", gather = true},
		{map = "-15,-52", changeMap = "top", gather = true},
		{map = "-15,-53", changeMap = "top", gather = true},
		{map = "-15,-54", changeMap = "top", gather = true},
		{map = "-15,-55", changeMap = "top", gather = true},
		{map = "-15,-56", changeMap = "top", gather = true},
		{map = "-15,-57", changeMap = "top", gather = true},
		{map = "-15,-58", changeMap = "top", gather = true},
		{map = "-15,-59", changeMap = "right", gather = true},
		{map = "-14,-59", changeMap = "bottom", gather = true},
		{map = "-14,-58", changeMap = "bottom", gather = true},
		{map = "-14,-57", changeMap = "bottom", gather = true},
		{map = "-14,-56", changeMap = "bottom", gather = true},
		{map = "-14,-55", changeMap = "bottom", gather = true},
		{map = "-14,-54", changeMap = "right", gather = true},
		{map = "-13,-54", changeMap = "bottom", gather = true},
		{map = "-13,-53", changeMap = "left", gather = true},
		{map = "-14,-53", changeMap = "bottom", gather = true},
		{map = "-14,-52", changeMap = "bottom", gather = true},
		{map = "-14,-51", changeMap = "bottom", gather = true},
		{map = "-14,-50", changeMap = "bottom", gather = true},
		{map = "-14,-48", changeMap = "bottom", gather = true},
		{map = "-14,-49", changeMap = "bottom", gather = true},
		{map = "-13,-47", changeMap = "top", gather = true},
		{map = "-13,-48", changeMap = "top", gather = true},
		{map = "-13,-49", changeMap = "top", gather = true},
		{map = "-13,-50", changeMap = "top", gather = true},
		{map = "-13,-51", changeMap = "top", gather = true},
		{map = "-13,-52", changeMap = "right", gather = true},
		{map = "-16,-45", changeMap = "right", gather = true},
		{map = "-15,-45", changeMap = "top", gather = true},
		{map = "-14,-47", changeMap = "bottom", gather = true},
		{map = "-14,-46", changeMap = "bottom", gather = true},
		{map = "-14,-45", changeMap = "right", gather = true},
		{map = "-13,-45", changeMap = "top", gather = true},
		{map = "-13,-46", changeMap = "top", gather = true},
		{map = "-12,-52", changeMap = "top", gather = true},
		{map = "-12,-53", changeMap = "top", gather = true},
		{map = "-12,-54", changeMap = "top", gather = true},
		{map = "-13,-55", changeMap = "top", gather = true},
		{map = "-13,-56", changeMap = "top", gather = true},
		{map = "-13,-57", changeMap = "top", gather = true},
		{map = "-13,-58", changeMap = "top", gather = true},
		{map = "-13,-59", changeMap = "right", gather = true},
		{map = "-12,-59", changeMap = "right", gather = true},
		{map = "-11,-59", changeMap = "bottom", gather = true},
		{map = "-11,-58", changeMap = "bottom", gather = true},
		{map = "-11,-57", changeMap = "left", gather = true},
		{map = "-12,-55", changeMap = "left", gather = true},
        }
    elseif (job:level(2) >= 90) and (job:level(2) < 100) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31, 101}
        return {
            {map = "0,0",custom = roulottes},
		{map = "-25,12", changeMap = "left", gather = true},
		{map = "-26,12", changeMap = "left", gather = true},
		{map = "-27,12", changeMap = "top", gather = true},
		{map = "-27,11", changeMap = "right", gather = true},
		{map = "-26,11", changeMap = "right", gather = true},
		{map = "-25,11", changeMap = "top", gather = true},
		{map = "-25,10", changeMap = "top", gather = true},
		{map = "-25,9", changeMap = "right", gather = true},
		{map = "-24,9", changeMap = "top", gather = true},
		{map = "-24,8", changeMap = "left", gather = true},
		{map = "-25,8", changeMap = "left", gather = true},
		{map = "-26,8", changeMap = "top", gather = true},
		{map = "-26,7", changeMap = "left", gather = true},
		{map = "-27,7", changeMap = "top", gather = true},
		{map = "-27,6", changeMap = "right", gather = true},
		{map = "-26,6", changeMap = "right", gather = true},
		{map = "-25,6", changeMap = "right", gather = true},
		{map = "-24,6", changeMap = "right", gather = true},
		{map = "-23,6", changeMap = "top", gather = true},
		{map = "-25,5", changeMap = "left", gather = true},
		{map = "-24,5", changeMap = "left", gather = true},
		{map = "-23,5", changeMap = "left", gather = true},
		{map = "-26,5", changeMap = "top", gather = true},
		{map = "-26,4", changeMap = "left", gather = true},
		{map = "-27,4", changeMap = "top", gather = true},
		{map = "-26,3", changeMap = "right", gather = true},
		{map = "-27,3", changeMap = "right", gather = true},
		{map = "-25,3", changeMap = "right", gather = true},
		{map = "-24,3", changeMap = "top", gather = true},
		{map = "-24,2", changeMap = "left", gather = true},
		{map = "-25,2", changeMap = "left", gather = true},
		{map = "-26,2", changeMap = "top", gather = true},
		{map = "-26,1", changeMap = "right", gather = true},
		{map = "-25,1", changeMap = "right", gather = true},
		{map = "-24,1", changeMap = "top", gather = true},
		{map = "-24,0", changeMap = "left", gather = true},
		{map = "-25,0", changeMap = "left", gather = true},
		{map = "-26,0", changeMap = "left", gather = true},
		{map = "-27,0", changeMap = "left", gather = true},
		{map = "-28,0", changeMap = "top", gather = true},
		{map = "-28,-1", changeMap = "right", gather = true},
		{map = "-27,-1", changeMap = "right", gather = true},
		{map = "-26,-1", changeMap = "right", gather = true},
		{map = "-25,-1", changeMap = "top", gather = true},
		{map = "-25,-2", changeMap = "left", gather = true},
		{map = "-26,-2", changeMap = "left", gather = true},
		{map = "-27,-2", changeMap = "top", gather = true},
		{map = "-27,-3", changeMap = "right", gather = true},
		{map = "-26,-3", changeMap = "right", gather = true},
		{map = "-25,-3", changeMap = "right", gather = true},
		{map = "-24,-3", changeMap = "bottom", gather = true},
		{map = "-24,-2", changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 100) and (job:level(2) < 110) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31, 101, 28}
        return {
            {map = "0,0", custom = otomai},
	{map = "-46,18", changeMap = "left", gather = true},
		{map = "-47,18", changeMap = "bottom", gather = true},
		{map = "-47,19", changeMap = "left", gather = true},
		{map = "-48,19", changeMap = "top", gather = true},
		{map = "-48,18", changeMap = "top", gather = true},
		{map = "-48,17", changeMap = "top", gather = true},
		{map = "-48,16", changeMap = "top", gather = true},
		{map = "-48,15", changeMap = "left", gather = true},
		{map = "-49,15", changeMap = "bottom", gather = true},
		{map = "-49,16", changeMap = "bottom", gather = true},
		{map = "-49,18", changeMap = "bottom", gather = true},
		{map = "-49,17", changeMap = "bottom", gather = true},
		{map = "-49,19", changeMap = "left", gather = true},
		{map = "-50,19", changeMap = "bottom", gather = true},
		{map = "-50,20", changeMap = "bottom", gather = true},
		{map = "-50,21", changeMap = "left", gather = true},
		{map = "-51,21", changeMap = "bottom", gather = true},
		{map = "-51,22", changeMap = "left", gather = true},
		{map = "-52,22", changeMap = "left", gather = true},
		{map = "-53,22", changeMap = "bottom", gather = true},
		{map = "-53,23", changeMap = "left", gather = true},
		{map = "-54,23", changeMap = "top", gather = true},
		{map = "-54,22", changeMap = "left", gather = true},
		{map = "-55,22", changeMap = "bottom", gather = true},
		{map = "-55,23", changeMap = "left", gather = true},
		{map = "-56,23", changeMap = "top", gather = true},
		{map = "-56,22", changeMap = "left", gather = true},
		{map = "-57,22", changeMap = "top", gather = true},
		{map = "-57,21", changeMap = "top", gather = true},
		{map = "-57,20", changeMap = "top", gather = true},
		{map = "-57,19", changeMap = "top", gather = true},
		{map = "-57,18", changeMap = "top", gather = true},
		{map = "-57,17", changeMap = "top", gather = true},
		{map = "-57,16", changeMap = "top", gather = true},
		{map = "-57,15", changeMap = "top", gather = true},
		{map = "-57,14", changeMap = "top", gather = true},
		{map = "-57,13", changeMap = "top", gather = true},
		{map = "-57,12", changeMap = "right", gather = true},
		{map = "-56,12", changeMap = "top", gather = true},
		{map = "-56,11", changeMap = "left", gather = true},
		{map = "-57,11", changeMap = "top", gather = true},
		{map = "-57,10", changeMap = "right", gather = true},
		{map = "-56,10", changeMap = "top", gather = true},
		{map = "-56,9", changeMap = "top", gather = true},
		{map = "-56,7", changeMap = "right", gather = true},
		{map = "-56,8", changeMap = "top", gather = true},
		{map = "-55,7", changeMap = "right", gather = true},
		{map = "-54,7", changeMap = "right", gather = true},
		{map = "-53,7", changeMap = "right", gather = true},
		{map = "-52,7", changeMap = "bottom", gather = true},
		{map = "-52,8", changeMap = "bottom", gather = true},
		{map = "-52,9", changeMap = "right", gather = true},
		{map = "-51,9", changeMap = "bottom", gather = true},
		{map = "-51,10", changeMap = "bottom", gather = true},
		{map = "-50,11", changeMap = "bottom", gather = true},
		{map = "-51,11", changeMap = "right", gather = true},
		{map = "-50,12", changeMap = "bottom", gather = true},
		{map = "-50,13", changeMap = "right", gather = true},
		{map = "-49,13", changeMap = "bottom", gather = true},
		{map = "-49,14", changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 110) and (job:level(2) < 120) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31, 101, 28, 108}
        return {
           {map = "0,0", custom = pandala},
	{map = "207619076", changeMap = "436" },
	{map = "206307842",changeMap = "bottom", gather = true},
	{map = "20,-28",changeMap = "bottom", gather = true},
{map = "20,-27",changeMap = "bottom", gather = true},
{map = "20,-26",changeMap = "right", gather = true},
{map = "21,-26",changeMap = "top", gather = true},
{map = "21,-27",changeMap = "right", gather = true},
{map = "22,-27",changeMap = "right", gather = true},
{map = "23,-27",changeMap = "top", gather = true},
{map = "23,-28",changeMap = "right", gather = true},
{map = "24,-28",changeMap = "right", gather = true},
{map = "24,-29",changeMap = "top", gather = true},
{map = "24,-30",changeMap = "top", gather = true},
{map = "24,-31",changeMap = "right", gather = true},
{map = "24,-32",changeMap = "top", gather = true},
{map = "24,-33",changeMap = "top", gather = true},
{map = "24,-34",changeMap = "right", gather = true},
{map = "25,-34",changeMap = "bottom", gather = true},
{map = "25,-33",changeMap = "bottom", gather = true},
{map = "25,-32",changeMap = "right", gather = true},
{map = "26,-32",changeMap = "bottom", gather = true},
{map = "25,-31",changeMap = "top", gather = true},
{map = "25,-30",changeMap = "left", gather = true},
{map = "25,-29",changeMap = "top", gather = true},
{map = "25,-28",changeMap = "top", gather = true},
{map = "26,-28",changeMap = "top", gather = true},
{map = "26,-29",changeMap = "right", gather = true},
{map = "27,-29",changeMap = "bottom", gather = true},
{map = "27,-30",changeMap = "bottom", gather = true},
{map = "26,-31",changeMap = "right", gather = true},
{map = "27,-31",changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 120) and (job:level(2) < 130) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31, 101, 28, 108, 35}
        return {
           {map = "0,0",custom = plainerocheuse},
		{map = "-17,-47", changeMap = "right", gather = true},
		{map = "-16,-47", changeMap = "bottom", gather = true},
		{map = "-16,-46", changeMap = "bottom", gather = true},
		{map = "-16,-45", changeMap = "bottom", gather = true},
		{map = "-16,-44", changeMap = "right", gather = true},
		{map = "-15,-44", changeMap = "right", gather = true},
		{map = "-14,-44", changeMap = "right", gather = true},
		{map = "-13,-44", changeMap = "top", gather = true},
		{map = "-13,-45", changeMap = "top", gather = true},
		{map = "-13,-46", changeMap = "right", gather = true},
		{map = "-12,-46", changeMap = "bottom", gather = true},
		{map = "-12,-45", changeMap = "right", gather = true},
		{map = "-11,-45", changeMap = "right", gather = true},
		{map = "-10,-45", changeMap = "bottom", gather = true},
		{map = "-10,-44", changeMap = "right", gather = true},
		{map = "-9,-44", changeMap = "top", gather = true},
		{map = "-9,-45", changeMap = "top", gather = true},
		{map = "-9,-46", changeMap = "left", gather = true},
		{map = "-10,-46", changeMap = "left", gather = true},
		{map = "-11,-46", changeMap = "top", gather = true},
		{map = "-11,-47", changeMap = "left", gather = true},
		{map = "-12,-47", changeMap = "top", gather = true},
		{map = "-12,-48", changeMap = "top", gather = true},
		{map = "-12,-49", changeMap = "left", gather = true},
		{map = "-13,-49", changeMap = "top", gather = true},
		{map = "-13,-50", changeMap = "right", gather = true},
		{map = "-12,-50", changeMap = "top", gather = true},
		{map = "-12,-51", changeMap = "top", gather = true},
		{map = "-12,-52", changeMap = "top", gather = true},
		{map = "-12,-53", changeMap = "top", gather = true},
		{map = "-12,-54", changeMap = "top", gather = true},
		{map = "-12,-55", changeMap = "top", gather = true},
		{map = "-12,-56", changeMap = "right", gather = true},
		{map = "-11,-56", changeMap = "top", gather = true},
		{map = "-11,-57", changeMap = "left", gather = true},
		{map = "-12,-57", changeMap = "top", gather = true},
		{map = "-12,-58", changeMap = "top", gather = true},
		{map = "-12,-59", changeMap = "right", gather = true},
		{map = "-11,-59", changeMap = "right", gather = true},
		{map = "-10,-59", changeMap = "right", gather = true},
		{map = "-9,-59", changeMap = "right", gather = true},
		{map = "-8,-59", changeMap = "right", gather = true},
		{map = "-7,-59", changeMap = "right", gather = true},
		{map = "-6,-58", changeMap = "bottom", gather = true},
		{map = "-6,-59", changeMap = "bottom", gather = true},
		{map = "-6,-57", changeMap = "right", gather = true},
		{map = "-5,-57", changeMap = "bottom", gather = true},
		{map = "-5,-56", changeMap = "bottom", gather = true},
		{map = "-5,-55", changeMap = "left", gather = true},
		{map = "-6,-55", changeMap = "bottom", gather = true},
		{map = "-6,-54", changeMap = "left", gather = true},
		{map = "-7,-54", changeMap = "top", gather = true},
		{map = "-7,-55", changeMap = "top", gather = true},
		{map = "-7,-56", changeMap = "right", gather = true},
        }
    elseif (job:level(2) >= 130) and (job:level(2) < 140) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31, 101, 28, 108, 35, 259}
        return {
           {map = "0,0", custom = otomai},
	{map = "-46,18", changeMap = "left", gather = true},
		{map = "-47,18", changeMap = "bottom", gather = true},
		{map = "-47,19", changeMap = "left", gather = true},
		{map = "-48,19", changeMap = "left", gather = true},
		{map = "-49,19", changeMap = "left", gather = true},
		{map = "-50,19", changeMap = "bottom", gather = true},
		{map = "-50,20", changeMap = "bottom", gather = true},
		{map = "-50,21", changeMap = "left", gather = true},
		{map = "-51,21", changeMap = "top", gather = true},
		{map = "-51,20", changeMap = "left", gather = true},
		{map = "-52,20", changeMap = "left", gather = true},
		{map = "-53,20", changeMap = "bottom", gather = true},
		{map = "-53,21", changeMap = "left", gather = true},
		{map = "-54,21", changeMap = "top", gather = true},
		{map = "-54,20", changeMap = "left", gather = true},
		{map = "-55,20", changeMap = "left", gather = true},
		{map = "-56,20", changeMap = "top", gather = true},
		{map = "-56,19", changeMap = "top", gather = true},
		{map = "-56,18", changeMap = "top", gather = true},
		{map = "-56,17", changeMap = "top", gather = true},
		{map = "-56,16", changeMap = "top", gather = true},
		{map = "-56,15", changeMap = "right", gather = true},
		{map = "-55,15", changeMap = "bottom", gather = true},
		{map = "-55,16", changeMap = "bottom", gather = true},
		{map = "-55,17", changeMap = "right", gather = true},
		{map = "-54,17", changeMap = "top", gather = true},
		{map = "-54,16", changeMap = "top", gather = true},
		{map = "-54,15", changeMap = "top", gather = true},
		{map = "-54,14", changeMap = "top", gather = true},
		{map = "-54,13", changeMap = "left", gather = true},
		{map = "-55,13", changeMap = "top", gather = true},
		{map = "-55,12", changeMap = "top", gather = true},
		{map = "-55,11", changeMap = "top", gather = true},
		{map = "-55,10", changeMap = "top", gather = true},
		{map = "-55,9", changeMap = "right", gather = true},
		{map = "-54,9", changeMap = "bottom", gather = true},
		{map = "-54,10", changeMap = "right", gather = true},
		{map = "-53,10", changeMap = "bottom", gather = true},
		{map = "-53,11", changeMap = "557", gather = true},
		{map = "-52,12", changeMap = "bottom", gather = true},
		{map = "-52,13", changeMap = "left", gather = true},
		{map = "-53,12", changeMap = "right", gather = true},
		{map = "-53,13", changeMap = "bottom", gather = true},
		{map = "-53,14", changeMap = "bottom", gather = true},
		{map = "-53,15", changeMap = "right", gather = true},
		{map = "-52,15", changeMap = "right", gather = true},
		{map = "-51,15", changeMap = "bottom", gather = true},
		{map = "-51,16", changeMap = "bottom", gather = true},
		{map = "-51,17", changeMap = "bottom", gather = true},
		{map = "-51,18", changeMap = "bottom", gather = true},
		{map = "-51,19", changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 140) and (job:level(2) < 150) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31, 101, 28, 108, 35, 259, 29}
        return {
            {map = "0,0", custom = otomai},
	{map = "-46,18", changeMap = "left", gather = true},
		{map = "-47,18", changeMap = "bottom", gather = true},
		{map = "-47,19", changeMap = "left", gather = true},
		{map = "-48,19", changeMap = "left", gather = true},
		{map = "-49,19", changeMap = "left", gather = true},
		{map = "-50,19", changeMap = "bottom", gather = true},
		{map = "-50,20", changeMap = "bottom", gather = true},
		{map = "-50,21", changeMap = "left", gather = true},
		{map = "-51,21", changeMap = "top", gather = true},
		{map = "-51,20", changeMap = "top", gather = true},
		{map = "-51,19", changeMap = "left", gather = true},
		{map = "-52,19", changeMap = "left", gather = true},
		{map = "-53,19", changeMap = "top", gather = true},
		{map = "-53,18", changeMap = "right", gather = true},
		{map = "-52,18", changeMap = "right", gather = true},
		{map = "-51,18", changeMap = "right", gather = true},
		{map = "-50,18", changeMap = "top", gather = true},
		{map = "-50,17", changeMap = "left", gather = true},
		{map = "-51,17", changeMap = "top", gather = true},
		{map = "-51,16", changeMap = "right", gather = true},
		{map = "-50,16", changeMap = "top", gather = true},
		{map = "-50,15", changeMap = "left", gather = true},
		{map = "-51,15", changeMap = "top", gather = true},
		{map = "-51,14", changeMap = "top", gather = true},
		{map = "-51,13", changeMap = "left", gather = true},
		{map = "-52,13", changeMap = "bottom", gather = true},
		{map = "-52,14", changeMap = "bottom", gather = true},
		{map = "-52,15", changeMap = "left", gather = true},
		{map = "-53,15", changeMap = "top", gather = true},
		{map = "-53,14", changeMap = "left", gather = true},
		{map = "-54,14", changeMap = "left", gather = true},
		{map = "-55,14", changeMap = "left", gather = true},
		{map = "-56,14", changeMap = "bottom", gather = true},
		{map = "-56,15", changeMap = "bottom", gather = true},
		{map = "-56,16", changeMap = "right", gather = true},
		{map = "-55,16", changeMap = "right", gather = true},
		{map = "-54,16", changeMap = "bottom", gather = true},
		{map = "-54,17", changeMap = "bottom", gather = true},
		{map = "-54,18", changeMap = "left", gather = true},
		{map = "-55,18", changeMap = "left", gather = true},
        }
    elseif (job:level(2) >= 150) and (job:level(2) < 160) then
        ELEMENTS_TO_GATHER = {1, 33, 34, 8, 98, 31, 101, 28, 108, 35, 259, 29, 121}
        return {
            {map = "0,0",custom = eleveurs},
		{map = "-99,14", changeMap = "left", gather = true},
		{map = "-16,1", changeMap = "bottom", gather = true},
		{map = "-16,3", changeMap = "bottom", gather = true},
		{map = "-16,2", changeMap = "bottom", gather = true},
		{map = "-16,4", changeMap = "bottom", gather = true},
		{map = "-16,5", changeMap = "bottom", gather = true},
		{map = "-16,6", changeMap = "left", gather = true},
		{map = "-17,6", changeMap = "left", gather = true},
		{map = "-18,6", changeMap = "left", gather = true},
		{map = "-19,6", changeMap = "top", gather = true},
		{map = "-19,5", changeMap = "top", gather = true},
		{map = "-19,4", changeMap = "top", gather = true},
		{map = "-19,3", changeMap = "top", gather = true},
		{map = "-19,2", changeMap = "top", gather = true},
		{map = "-19,1", changeMap = "top", gather = true},
		{map = "-19,0", changeMap = "top", gather = true},
		{map = "-20,0", changeMap = "left", gather = true},
		{map = "-21,0", changeMap = "top", gather = true},
		{map = "-21,-1", changeMap = "top", gather = true},
		{map = "-21,-2", changeMap = "right", gather = true},
		{map = "-20,-2", changeMap = "right", gather = true},
		{map = "-19,-2", changeMap = "right", gather = true},
		{map = "-18,-2", changeMap = "right", gather = true},
		{map = "-17,-2", changeMap = "top", gather = true},
		{map = "-17,-3", changeMap = "left", gather = true},
		{map = "-18,-3", changeMap = "top", gather = true},
		{map = "-18,-4", changeMap = "top", gather = true},
		{map = "-18,-5", changeMap = "top", gather = true},
		{map = "-18,-6", changeMap = "right", gather = true},
		{map = "-17,-6", changeMap = "right", gather = true},
		{map = "-16,-6", changeMap = "right", gather = true},
		{map = "-15,-6", changeMap = "bottom", gather = true},
		{map = "-15,-5", changeMap = "left", gather = true},
		{map = "-16,-5", changeMap = "bottom", gather = true},
		{map = "-16,-4", changeMap = "right", gather = true},
		{map = "-15,-4", changeMap = "bottom", gather = true},
		{map = "-15,-3", changeMap = "left", gather = true},
		{map = "-16,-3", changeMap = "bottom", gather = true},
		{map = "-16,-2", changeMap = "right", gather = true},
		{map = "-15,-2", changeMap = "right", gather = true},
		{map = "-14,-2", changeMap = "right", gather = true},
		{map = "-13,-2", changeMap = "right", gather = true},
		{map = "-12,-2", changeMap = "bottom", gather = true},
		{map = "-12,-1", changeMap = "left", gather = true},
		{map = "-13,-1", changeMap = "left", gather = true},
		{map = "-14,-1", changeMap = "bottom", gather = true},
		{map = "-14,0", changeMap = "right", gather = true},
		{map = "-13,0", changeMap = "right", gather = true},
		{map = "-12,0", changeMap = "bottom", gather = true},
		{map = "-12,1", changeMap = "bottom", gather = true},
		{map = "-12,2", changeMap = "left", gather = true},
		{map = "-13,2", changeMap = "bottom", gather = true},
		{map = "-13,3", changeMap = "bottom", gather = true},
		{map = "-13,4", changeMap = "bottom", gather = true},
		{map = "-13,5", changeMap = "bottom", gather = true},
		{map = "-13,6", changeMap = "bottom", gather = true},
		{map = "-13,7", changeMap = "left", gather = true},
		{map = "-14,7", changeMap = "left", gather = true},
		{map = "-15,7", changeMap = "left", gather = true},
		{map = "-19,-1", changeMap = "left", gather = true},
		{map = "-20,-1", changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 160) and (job:level(2) < 170) then
        ELEMENTS_TO_GATHER = {
            1, 33, 34, 8, 98, 31, 101, 28, 108, 35, 259, 29, 121, 32
        }
        return {
           {map = "0,0",custom = plainerocheuse},
		{map = "-17,-47", changeMap = "top", gather = true},
		{map = "-17,-48", changeMap = "top", gather = true},
		{map = "-17,-49", changeMap = "top", gather = true},
		{map = "-17,-50", changeMap = "top", gather = true},
		{map = "-17,-51", changeMap = "top", gather = true},
		{map = "-17,-52", changeMap = "top", gather = true},
		{map = "-17,-53", changeMap = "top", gather = true},
		{map = "-17,-54", changeMap = "top", gather = true},
		{map = "-17,-55", changeMap = "top", gather = true},
		{map = "-17,-56", changeMap = "top", gather = true},
		{map = "-16,-57", changeMap = "right", gather = true},
		{map = "-15,-57", changeMap = "bottom", gather = true},
		{map = "-15,-56", changeMap = "bottom", gather = true},
		{map = "-15,-54", changeMap = "bottom", gather = true},
		{map = "-15,-55", changeMap = "bottom", gather = true},
		{map = "-15,-53", changeMap = "bottom", gather = true},
		{map = "-15,-52", changeMap = "right", gather = true},
		{map = "-14,-52", changeMap = "bottom", gather = true},
		{map = "-14,-51", changeMap = "left", gather = true},
		{map = "-15,-51", changeMap = "bottom", gather = true},
		{map = "-15,-50", changeMap = "bottom", gather = true},
		{map = "-15,-49", changeMap = "bottom", gather = true},
		{map = "-14,-48", changeMap = "right", gather = true},
		{map = "-15,-48", changeMap = "right", gather = true},
		{map = "-13,-48", changeMap = "top", gather = true},
		{map = "-13,-49", changeMap = "top", gather = true},
		{map = "-13,-50", changeMap = "right", gather = true},
		{map = "-12,-50", changeMap = "bottom", gather = true},
		{map = "-12,-49", changeMap = "bottom", gather = true},
		{map = "-12,-48", changeMap = "bottom", gather = true},
		{map = "-12,-47", changeMap = "left", gather = true},
		{map = "-13,-47", changeMap = "bottom", gather = true},
		{map = "-13,-46", changeMap = "right", gather = true},
		{map = "-12,-46", changeMap = "right", gather = true},
		{map = "-11,-46", changeMap = "right", gather = true},
		{map = "-10,-46", changeMap = "right", gather = true},
		{map = "-9,-46", changeMap = "bottom", gather = true},
		{map = "-9,-45", changeMap = "bottom", gather = true},
		{map = "-9,-44", changeMap = "left", gather = true},
		{map = "-10,-44", changeMap = "top", gather = true},
		{map = "-10,-45", changeMap = "left", gather = true},
		{map = "-11,-45", changeMap = "bottom", gather = true},
		{map = "-11,-44", changeMap = "bottom", gather = true},
		{map = "-11,-43", changeMap = "left", gather = true},
		{map = "-12,-43", changeMap = "bottom", gather = true},
		{map = "-12,-42", changeMap = "right", gather = true},
		{map = "-11,-42", changeMap = "right", gather = true},
		{map = "-10,-42", changeMap = "right", gather = true},
		{map = "-17,-57", changeMap = "left", gather = true},
		{map = "-18,-57", changeMap = "top", gather = true},
		{map = "-18,-58", changeMap = "right", gather = true},
		{map = "-17,-58", changeMap = "right", gather = true},
		{map = "-16,-58", changeMap = "bottom", gather = true},
        }
    elseif (job:level(2) >= 170) and (job:level(2) < 180) then
        ELEMENTS_TO_GATHER = {
            1, 33, 34, 8, 98, 31, 101, 28, 108, 35, 259, 29, 121, 32, 109
        }
        return {
            {map = "0,0", custom = pandala},
	{map = "207619076", changeMap = "436" },
	{map = "206307842",changeMap = "top", gather = true},
	{map = "20,-30",changeMap = "left", gather = true},
		{map = "19,-30",changeMap = "left", gather = true},
		{map = "18,-30",changeMap = "left", gather = true},
		{map = "17,-30", changeMap = "left", gather = true},
		{map = "16,-30", changeMap = "top", gather = true},
		{map = "16,-31", changeMap = "right", gather = true},
		{map = "17,-31", changeMap = "right", gather = true},
		{map = "18,-31", changeMap = "top", gather = true},
		{map = "17,-32", changeMap = "left", gather = true},
		{map = "18,-32", changeMap = "left", gather = true},
		{map = "16,-32", changeMap = "left", gather = true},
		{map = "15,-32", changeMap = "left", gather = true},
		{map = "14,-32", changeMap = "top", gather = true},
		{map = "14,-33", changeMap = "right", gather = true},
		{map = "15,-33", changeMap = "right", gather = true},
		{map = "16,-33", changeMap = "right", gather = true},
		{map = "17,-33", changeMap = "right", gather = true},
		{map = "18,-33", changeMap = "top", gather = true},
		{map = "18,-34", changeMap = "left", gather = true},
		{map = "16,-34", changeMap = "left", gather = true},
		{map = "17,-34", changeMap = "left", gather = true},
		{map = "15,-34", changeMap = "top", gather = true},
		{map = "15,-35", changeMap = "right", gather = true},
		{map = "16,-35", changeMap = "right", gather = true},
		{map = "17,-35", changeMap = "right", gather = true},
		{map = "18,-35", changeMap = "top", gather = true},
        }
    elseif (job:level(2) >= 180) and (job:level(2) < 200) then
        ELEMENTS_TO_GATHER = {
            1, 8, 28, 29, 30, 31, 32, 33, 34, 35, 101, 98, 108, 109, 110, 133,
            259
        }
        return {
            {map = "0,0",custom = plainerocheuse},
		{map = "-17,-47", changeMap = "top", gather = true},
		{map = "-17,-48", changeMap = "top", gather = true},
		{map = "-17,-49", changeMap = "top", gather = true},
		{map = "-17,-50", changeMap = "top", gather = true},
		{map = "-17,-51", changeMap = "top", gather = true},
		{map = "-17,-52", changeMap = "top", gather = true},
		{map = "-17,-53", changeMap = "top", gather = true},
		{map = "-17,-54", changeMap = "top", gather = true},
		{map = "-16,-55", changeMap = "top", gather = true},
		{map = "-16,-56", changeMap = "top", gather = true},
		{map = "-16,-57", changeMap = "top", gather = true},
		{map = "-16,-58", changeMap = "top", gather = true},
		{map = "-16,-59", changeMap = "top", gather = true},
		{map = "-16,-60", changeMap = "zaap(8,232,158861826)", gather = true},
		{map = "-17,-60", changeMap = "top", gather = true},
		{map = "-17,-61", changeMap = "top", gather = true},
		{map = "-17,-62", changeMap = "left", gather = true},
		{map = "-18,-62", changeMap = "bottom", gather = true},
		{map = "-18,-61", changeMap = "zaap(523,463,158860801)", gather = true},
		{map = "-18,-60", changeMap = "zaap(430,461,158860802)", gather = true},
		{map = "-18,-59", changeMap = "bottom", gather = true},
		{map = "-18,-58", changeMap = "bottom", gather = true},
		{map = "-18,-57", changeMap = "left", gather = true},
		{map = "-19,-57", changeMap = "bottom", gather = true},
		{map = "-19,-56", changeMap = "right", gather = true},
		{map = "-18,-56", changeMap = "bottom", gather = true},
		{map = "-18,-55", changeMap = "bottom", gather = true},
		{map = "-17,-55", changeMap = "right", gather = true},
		{map = "-18,-54", changeMap = "left", gather = true},
		{map = "-19,-54", changeMap = "left", gather = true},
		{map = "-20,-54", changeMap = "left", gather = true},
		{map = "-21,-54", changeMap = "bottom", gather = true},
		{map = "-21,-53", changeMap = "bottom", gather = true},
		{map = "-21,-52", changeMap = "bottom", gather = true},
		{map = "-21,-51", changeMap = "bottom", gather = true},
		{map = "-21,-50", changeMap = "bottom", gather = true},
		{map = "-21,-49", changeMap = "bottom", gather = true},
		{map = "-21,-48", changeMap = "bottom", gather = true},
		{map = "-21,-47", changeMap = "bottom", gather = true},
		{map = "-21,-46", changeMap = "bottom", gather = true},
		{map = "-21,-45", changeMap = "bottom", gather = true},
		{map = "-21,-44", changeMap = "left", gather = true},
		{map = "-22,-44", changeMap = "left", gather = true},
		{map = "-23,-44", changeMap = "bottom", gather = true},
		{map = "-23,-43", changeMap = "right", gather = true},
		{map = "-22,-43", changeMap = "right", gather = true},
		{map = "-21,-43", changeMap = "bottom", gather = true},
		{map = "-21,-42", changeMap = "bottom", gather = true},
		{map = "-21,-41", changeMap = "right", gather = true},
		{map = "-20,-41", changeMap = "right", gather = true},
		{map = "-19,-41", changeMap = "top", gather = true},
		{map = "-19,-42", changeMap = "right", gather = true},
		{map = "-18,-42", changeMap = "bottom", gather = true},
		{map = "-18,-41", changeMap = "right", gather = true},
		{map = "-17,-41", changeMap = "right", gather = true},
		{map = "-16,-41", changeMap = "right", gather = true},
		{map = "-15,-41", changeMap = "top", gather = true},
		{map = "-15,-42", changeMap = "top", gather = true},
		{map = "-15,-43", changeMap = "top", gather = true},
		{map = "-15,-44", changeMap = "top", gather = true},
		{map = "-15,-45", changeMap = "top", gather = true},
		{map = "-15,-46", changeMap = "top", gather = true},
		{map = "-15,-47", changeMap = "top", gather = true},
		{map = "-15,-48", changeMap = "top", gather = true},
		{map = "-15,-49", changeMap = "top", gather = true},
		{map = "-15,-50", changeMap = "top", gather = true},
		{map = "-15,-51", changeMap = "top", gather = true},
		{map = "-15,-52", changeMap = "top", gather = true},
		{map = "-15,-54", changeMap = "top", gather = true},
		{map = "-15,-53", changeMap = "top", gather = true},
		{map = "-15,-55", changeMap = "top", gather = true},
		{map = "-15,-56", changeMap = "top", gather = true},
		{map = "-15,-57", changeMap = "top", gather = true},
		{map = "-15,-58", changeMap = "top", gather = true},
		{map = "-15,-59", changeMap = "right", gather = true},
		{map = "-14,-59", changeMap = "right", gather = true},
		{map = "-13,-59", changeMap = "right", gather = true},
		{map = "-12,-59", changeMap = "right", gather = true},
		{map = "-11,-59", changeMap = "right", gather = true},
		{map = "-9,-59", changeMap = "right", gather = true},
		{map = "-10,-59", changeMap = "right", gather = true},
		{map = "-8,-59", changeMap = "right", gather = true},
		{map = "-7,-58", changeMap = "bottom", gather = true},
		{map = "-7,-57", changeMap = "left", gather = true},
		{map = "-8,-58", changeMap = "right", gather = true},
		{map = "-7,-58", changeMap = "bottom", gather = true},
		{map = "-7,-57", changeMap = "left", gather = true},
		{map = "-8,-57", changeMap = "bottom", gather = true},
		{map = "-8,-56", changeMap = "bottom", gather = true},
		{map = "-8,-55", changeMap = "bottom", gather = true},
		{map = "-8,-54", changeMap = "bottom", gather = true},
		{map = "-8,-53", changeMap = "bottom", gather = true},
		{map = "-8,-52", changeMap = "bottom", gather = true},
		{map = "-8,-50", changeMap = "bottom", gather = true},
		{map = "-8,-49", changeMap = "bottom", gather = true},
		{map = "-8,-48", changeMap = "bottom", gather = true},
		{map = "-8,-47", changeMap = "bottom", gather = true},
		{map = "-8,-46", changeMap = "right", gather = true},
		{map = "-7,-46", changeMap = "right", gather = true},
		{map = "-6,-46", changeMap = "right", gather = true},
		{map = "-5,-46", changeMap = "bottom", gather = true},
		{map = "-5,-45", changeMap = "bottom", gather = true},
		{map = "-5,-44", changeMap = "bottom", gather = true},
        }
    end
end

function bank()
    return {
        { map = "0,0", changeMap = "zaap(121,217,191105026)" },
		{ map = "5,-18", changeMap = "left" },
		{ map = "191104002", changeMap = "247" },
		{ map = "192415750", custom = hiboux},
    }
end

function lost()
	return {
		enterHavenbag()
	}
end

function phenix() 
    return {} 
end

function havresac()
    global:delay(2500)
    global:sendKey(72)
    global:delay(2500)
end

function hiboux()
    npc:npcBank(-1, -1)
    global:delay(2500)
    storage:putAllItems()
    global:leaveDialog()
end