MAX_PODS = 90

function havresac()
    global:delay(1000)
    global:sendKey(72)
    global:delay(1000)
end

function lost()
	havresac()
end

function hiboux()
    npc:npcBank(-1,-1)
    global:delay(2500)
    storage:putAllItems()
    global:leaveDialog()
end

function frigost()
	global:delay(2500)
	map:changeMap("zaap(303,206,54172969)")
	global:delay(2500)
end

function eleveurs()
	global:delay(2500)
	map:changeMap("zaap(313,240,73400320)")
	global:delay(2500)
end

function astrub()
	global:delay(2500)
	map:changeMap("zaap(125,196,191105026)")
	global:delay(2500)
end

function sortir()
	global:clickPosition(134,368,false)
end

function click2()
	global:clickPosition(430,461,false)
end

function click3()
	global:clickPosition(330,464,false)
end
function lacDeCania()
	global:delay(2500)
	map:changeMap("zaap(489,137,156240386)")
	global:delay(2500)
end

function rivage()
	global:delay(2500)
	map:changeMap("zaap(352,216,88085249)")
	global:delay(2500)
end

function otomai()
	global:delay(2500)
	map:changeMap("zaap(304,204,154642)")
	global:delay(2500)
end

function pandala()
	global:delay(2500)
	map:changeMap("zaap(143,201,207619076)")
	global:delay(2500)
end

function coin()
	global:delay(2500)
	map:changeMap("zaap(424,205,88082704)")
	global:delay(2500)
end

function scarafeuille()
	global:delay(2500)
	map:changeMap("zaap(150,289,88212481)")
	global:delay(2500)
end

function click()
	global:clickPosition(598,433,false)
end

function move()
	if (job:level(36) < 10) then
        ELEMENTS_TO_GATHER = {75}
	return {
		{map = "0,0" , custom = rivage},
		{map = "10,22", changeMap = "right", gather = true},
		{map = "11,22", changeMap = "top", gather = true},
		{map = "11,21", changeMap = "top", gather = true},
		{map = "11,20", changeMap = "right", gather = true},
		{map = "12,20", changeMap = "top", gather = true},
		{map = "12,19", changeMap = "top", gather = true},
		{map = "12,18", changeMap = "right", gather = true},
		{map = "13,18", changeMap = "top", gather = true},
		{map = "13,17", changeMap = "top", gather = true},
		{map = "13,16", changeMap = "top", gather = true},
		{map = "13,15", changeMap = "left", gather = true},
		{map = "12,15", changeMap = "top", gather = true},
		{map = "12,14", changeMap = "top", gather = true},
		{map = "12,13", changeMap = "top", gather = true},
		{map = "12,12", changeMap = "left", gather = true},
		{map = "11,12", changeMap = "left", gather = true},
		{map = "10,12", changeMap = "left", gather = true},
		{map = "9,12", changeMap = "bottom", gather = true},
		{map = "9,13", changeMap = "left", gather = true},
		{map = "8,13", changeMap = "bottom", gather = true},
		{map = "8,14", changeMap = "left", gather = true},
		{map = "7,14", changeMap = "bottom", gather = true},
		{map = "7,15", changeMap = "bottom", gather = true},
		{map = "7,16", changeMap = "bottom", gather = true},
		{map = "7,17", changeMap = "bottom", gather = true},
		{map = "7,18", changeMap = "bottom", gather = true},
		{map = "7,19", changeMap = "right", gather = true},
		{map = "8,19", changeMap = "right", gather = true},
		{map = "9,19", changeMap = "right", gather = true},
		{map = "10,19", changeMap = "right", gather = true},
	}
	elseif (job:level(36) >= 10) and (job:level(36) < 20) then
		ELEMENTS_TO_GATHER = {71,75}
	return {
		{map = "0,0", custom = coin},
		{map = "12,9", changeMap = "left", gather = true},
		{map = "11,9", changeMap = "bottom", gather = true},
		{map = "11,10", changeMap = "right", gather = true},
		{map = "12,11", changeMap = "bottom", gather = true},
		{map = "15,20", changeMap = "left", gather = true},
		{map = "11,29", changeMap = "left", gather = true},
		{map = "5,7", changeMap = "right", gather = true},
		{map = "6,7", changeMap = "right", gather = true},
		{map = "7,7", changeMap = "right", gather = true},
		{map = "8,7", changeMap = "right", gather = true},
		{map = "9,7", changeMap = "right", gather = true},
		{map = "10,7", changeMap = "right", gather = true},
		{map = "11,7", changeMap = "top", gather = true},
		{map = "11,6", changeMap = "top", gather = true},
		{map = "11,5", changeMap = "top", gather = true},
		{map = "11,4", changeMap = "top", gather = true},
		{map = "11,3", changeMap = "right", gather = true},
		{map = "12,3", changeMap = "bottom", gather = true},
		{map = "12,4", changeMap = "right", gather = true},
		{map = "13,4", changeMap = "bottom", gather = true},
		{map = "13,5", changeMap = "bottom", gather = true},
		{map = "13,6", changeMap = "bottom", gather = true},
		{map = "13,7", changeMap = "bottom", gather = true},
		{map = "13,8", changeMap = "left", gather = true},
		{map = "12,8", changeMap = "bottom", gather = true},
		{map = "12,10", changeMap = "bottom", gather = true},
		{map = "12,12", changeMap = "right", gather = true},
		{map = "13,12", changeMap = "right", gather = true},
		{map = "14,12", changeMap = "bottom", gather = true},
		{map = "14,13", changeMap = "bottom", gather = true},
		{map = "14,14", changeMap = "bottom", gather = true},
		{map = "14,15", changeMap = "right", gather = true},
		{map = "15,15", changeMap = "bottom", gather = true},
		{map = "15,16", changeMap = "bottom", gather = true},
		{map = "15,17", changeMap = "bottom", gather = true},
		{map = "15,18", changeMap = "bottom", gather = true},
		{map = "15,19", changeMap = "bottom", gather = true},
		{map = "14,20", changeMap = "left", gather = true},
		{map = "13,20", changeMap = "bottom", gather = true},
		{map = "13,21", changeMap = "bottom", gather = true},
		{map = "13,22", changeMap = "left", gather = true},
		{map = "12,22", changeMap = "left", gather = true},
		{map = "11,22", changeMap = "left", gather = true},
		{map = "10,22", changeMap = "left", gather = true},
		{map = "9,22", changeMap = "top", gather = true},
		{map = "9,21", changeMap = "left", gather = true},
		{map = "8,21", changeMap = "bottom", gather = true},
		{map = "8,22", changeMap = "left", gather = true},
		{map = "7,22", changeMap = "bottom", gather = true},
		{map = "7,23", changeMap = "left", gather = true},
		{map = "6,23", changeMap = "left", gather = true},
		{map = "5,23", changeMap = "left", gather = true},
		{map = "4,23", changeMap = "bottom", gather = true},
		{map = "4,24", changeMap = "bottom", gather = true},
		{map = "4,25", changeMap = "bottom", gather = true},
		{map = "4,26", changeMap = "right", gather = true},
		{map = "5,26", changeMap = "bottom", gather = true},
		{map = "5,27", changeMap = "bottom", gather = true},
		{map = "5,28", changeMap = "right", gather = true},
		{map = "6,28", changeMap = "right", gather = true},
		{map = "7,28", changeMap = "bottom", gather = true},
		{map = "7,29", changeMap = "right", gather = true},
		{map = "8,29", changeMap = "right", gather = true},
		{map = "9,29", changeMap = "top", gather = true},
		{map = "9,28", changeMap = "right", gather = true},
		{map = "10,28", changeMap = "right", gather = true},
		{map = "11,28", changeMap = "bottom", gather = true},
		{map = "10,29", changeMap = "bottom", gather = true},
		{map = "10,30", changeMap = "left", gather = true},
		{map = "9,30", changeMap = "left", gather = true},
		{map = "8,30", changeMap = "bottom", gather = true},
		{map = "8,31", changeMap = "left", gather = true},
		{map = "7,31", changeMap = "left", gather = true},
		{map = "6,31", changeMap = "left", gather = true},
	}
	elseif (job:level(36) >= 20) and (job:level(36) < 30) then
		ELEMENTS_TO_GATHER = {71,75,74}
	return {
		{map = "0,0",custom = rivage},
		{map = "10,22", changeMap = "top", gather = true},
		{map = "10,21", changeMap = "top", gather = true},
		{map = "10,20", changeMap = "right", gather = true},
		{map = "11,20", changeMap = "right", gather = true},
		{map = "12,20", changeMap = "top", gather = true},
		{map = "12,19", changeMap = "top", gather = true},
		{map = "12,18", changeMap = "right", gather = true},
		{map = "13,18", changeMap = "top", gather = true},
		{map = "13,17", changeMap = "top", gather = true},
		{map = "13,16", changeMap = "top", gather = true},
		{map = "13,15", changeMap = "left", gather = true},
		{map = "12,15", changeMap = "top", gather = true},
		{map = "12,14", changeMap = "top", gather = true},
		{map = "11,12", changeMap = "left", gather = true},
		{map = "10,12", changeMap = "left", gather = true},
		{map = "9,12", changeMap = "bottom", gather = true},
		{map = "9,13", changeMap = "left", gather = true},
		{map = "8,13", changeMap = "bottom", gather = true},
		{map = "8,14", changeMap = "left", gather = true},
		{map = "7,14", changeMap = "bottom", gather = true},
		{map = "7,15", changeMap = "bottom", gather = true},
		{map = "7,16", changeMap = "bottom", gather = true},
		{map = "7,17", changeMap = "bottom", gather = true},
		{map = "7,18", changeMap = "right", gather = true},
		{map = "8,18", changeMap = "bottom", gather = true},
		{map = "8,19", changeMap = "right", gather = true},
		{map = "9,19", changeMap = "right", gather = true},
		{map = "12,13", changeMap = "top", gather = true},
		{map = "12,12", changeMap = "left", gather = true},
	}
	elseif (job:level(36) >= 30) and (job:level(36) < 40) then
		ELEMENTS_TO_GATHER = {71,75,74,77}
	return {
		{map = "0,0" , custom = coin},
		{map = "5,7", changeMap = "right", gather = true},
		{map = "6,7", changeMap = "right", gather = true},
		{map = "7,7", changeMap = "right", gather = true},
		{map = "8,7", changeMap = "right", gather = true},
		{map = "9,7", changeMap = "right", gather = true},
		{map = "10,7", changeMap = "right", gather = true},
		{map = "11,7", changeMap = "top", gather = true},
		{map = "11,6", changeMap = "top", gather = true},
		{map = "11,4", changeMap = "top", gather = true},
		{map = "11,5", changeMap = "top", gather = true},
		{map = "11,3", changeMap = "right", gather = true},
		{map = "12,3", changeMap = "bottom", gather = true},
		{map = "12,4", changeMap = "right", gather = true},
		{map = "13,4", changeMap = "bottom", gather = true},
		{map = "13,5", changeMap = "bottom", gather = true},
		{map = "13,6", changeMap = "bottom", gather = true},
		{map = "13,7", changeMap = "bottom", gather = true},
		{map = "13,8", changeMap = "left", gather = true},
		{map = "12,8", changeMap = "bottom", gather = true},
		{map = "12,10", changeMap = "bottom", gather = true},
		{map = "12,9", changeMap = "left", gather = true},
		{map = "11,9", changeMap = "bottom", gather = true},
		{map = "11,10", changeMap = "right", gather = true},
		{map = "12,11", changeMap = "bottom", gather = true},
		{map = "15,20", changeMap = "left", gather = true},
		{map = "14,20", changeMap = "bottom", gather = true},
		{map = "14,21", changeMap = "bottom", gather = true},
		{map = "14,22", changeMap = "left", gather = true},
		{map = "11,29", changeMap = "left", gather = true},
		{map = "9,30", changeMap = "left", gather = true},
		{map = "12,12", changeMap = "right", gather = true},
		{map = "13,12", changeMap = "right", gather = true},
		{map = "14,12", changeMap = "bottom", gather = true},
		{map = "14,13", changeMap = "bottom", gather = true},
		{map = "14,14", changeMap = "right", gather = true},
		{map = "15,14", changeMap = "bottom", gather = true},
		{map = "15,15", changeMap = "bottom", gather = true},
		{map = "15,16", changeMap = "bottom", gather = true},
		{map = "15,17", changeMap = "bottom", gather = true},
		{map = "15,18", changeMap = "bottom", gather = true},
		{map = "15,19", changeMap = "bottom", gather = true},
		{map = "13,22", changeMap = "left", gather = true},
		{map = "12,22", changeMap = "left", gather = true},
		{map = "11,22", changeMap = "left", gather = true},
		{map = "10,22", changeMap = "left", gather = true},
		{map = "9,22", changeMap = "left", gather = true},
		{map = "8,22", changeMap = "left", gather = true},
		{map = "7,22", changeMap = "bottom", gather = true},
		{map = "7,23", changeMap = "left", gather = true},
		{map = "6,23", changeMap = "left", gather = true},
		{map = "5,23", changeMap = "left", gather = true},
		{map = "4,23", changeMap = "bottom", gather = true},
		{map = "4,25", changeMap = "bottom", gather = true},
		{map = "4,24", changeMap = "bottom", gather = true},
		{map = "4,26", changeMap = "bottom", gather = true},
		{map = "4,27", changeMap = "bottom", gather = true},
		{map = "4,28", changeMap = "right", gather = true},
		{map = "5,28", changeMap = "right", gather = true},
		{map = "6,28", changeMap = "bottom", gather = true},
		{map = "6,29", changeMap = "right", gather = true},
		{map = "7,29", changeMap = "right", gather = true},
		{map = "8,29", changeMap = "right", gather = true},
		{map = "9,29", changeMap = "top", gather = true},
		{map = "9,28", changeMap = "right", gather = true},
		{map = "10,28", changeMap = "right", gather = true},
		{map = "11,28", changeMap = "bottom", gather = true},
		{map = "10,29", changeMap = "bottom", gather = true},
		{map = "10,30", changeMap = "left", gather = true},
		{map = "8,30", changeMap = "bottom", gather = true},
		{map = "8,31", changeMap = "left", gather = true},
		{map = "7,31", changeMap = "left", gather = true},
	}
	elseif (job:level(36) >= 40) and (job:level(36) < 50) then
		ELEMENTS_TO_GATHER = {71,75,74,77,76}
	return {
		{map = "0,0" , custom = rivage},
		{map = "10,22", changeMap = "top", gather = true},
		{map = "10,21", changeMap = "top", gather = true},
		{map = "10,20", changeMap = "right", gather = true},
		{map = "11,20", changeMap = "right", gather = true},
		{map = "12,20", changeMap = "top", gather = true},
		{map = "12,19", changeMap = "top", gather = true},
		{map = "12,18", changeMap = "right", gather = true},
		{map = "13,18", changeMap = "top", gather = true},
		{map = "13,17", changeMap = "top", gather = true},
		{map = "13,16", changeMap = "top", gather = true},
		{map = "13,15", changeMap = "left", gather = true},
		{map = "12,15", changeMap = "top", gather = true},
		{map = "12,14", changeMap = "top", gather = true},
		{map = "12,13", changeMap = "top", gather = true},
		{map = "12,12", changeMap = "left", gather = true},
		{map = "10,12", changeMap = "left", gather = true},
		{map = "11,12", changeMap = "left", gather = true},
		{map = "9,12", changeMap = "bottom", gather = true},
		{map = "9,13", changeMap = "left", gather = true},
		{map = "8,13", changeMap = "bottom", gather = true},
		{map = "8,14", changeMap = "left", gather = true},
		{map = "7,14", changeMap = "bottom", gather = true},
		{map = "7,15", changeMap = "bottom", gather = true},
		{map = "7,16", changeMap = "bottom", gather = true},
		{map = "7,17", changeMap = "bottom", gather = true},
		{map = "7,18", changeMap = "left", gather = true},
		{map = "6,18", changeMap = "bottom", gather = true},
		{map = "6,19", changeMap = "bottom", gather = true},
		{map = "6,20", changeMap = "right", gather = true},
		{map = "7,20", changeMap = "right", gather = true},
		{map = "8,20", changeMap = "top", gather = true},
		{map = "8,19", changeMap = "right", gather = true},
		{map = "9,19", changeMap = "top", gather = true},
	}
	elseif (job:level(36) >= 50) and (job:level(36) < 60) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78}
	return {
		{map = "0,0", custom = coin},
		{map = "5,7", changeMap = "right", gather = true},
		{map = "6,7", changeMap = "right", gather = true},
		{map = "7,7", changeMap = "right", gather = true},
		{map = "8,7", changeMap = "right", gather = true},
		{map = "9,7", changeMap = "right", gather = true},
		{map = "10,7", changeMap = "top", gather = true},
		{map = "10,6", changeMap = "top", gather = true},
		{map = "10,5", changeMap = "top", gather = true},
		{map = "10,4", changeMap = "top", gather = true},
		{map = "10,3", changeMap = "right", gather = true},
		{map = "13,4", changeMap = "bottom", gather = true},
		{map = "13,5", changeMap = "bottom", gather = true},
		{map = "13,6", changeMap = "bottom", gather = true},
		{map = "13,7", changeMap = "bottom", gather = true},
		{map = "13,8", changeMap = "left", gather = true},
		{map = "12,8", changeMap = "bottom", gather = true},
		{map = "12,10", changeMap = "bottom", gather = true},
		{map = "12,11", changeMap = "bottom", gather = true},
		{map = "12,12", changeMap = "right", gather = true},
		{map = "13,12", changeMap = "bottom", gather = true},
		{map = "13,13", changeMap = "bottom", gather = true},
		{map = "13,14", changeMap = "bottom", gather = true},
		{map = "13,15", changeMap = "right", gather = true},
		{map = "14,15", changeMap = "right", gather = true},
		{map = "15,15", changeMap = "bottom", gather = true},
		{map = "15,16", changeMap = "bottom", gather = true},
		{map = "15,17", changeMap = "bottom", gather = true},
		{map = "15,18", changeMap = "bottom", gather = true},
		{map = "15,19", changeMap = "bottom", gather = true},
		{map = "15,20", changeMap = "bottom", gather = true},
		{map = "11,3", changeMap = "right", gather = true},
		{map = "12,3", changeMap = "bottom", gather = true},
		{map = "12,4", changeMap = "right", gather = true},
		{map = "12,9", changeMap = "left", gather = true},
		{map = "11,9", changeMap = "bottom", gather = true},
		{map = "11,10", changeMap = "right", gather = true},
	}
	elseif (job:level(36) >= 60) and (job:level(36) < 70) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79}
	return {
		{map = "0,0", custom = rivage},
		{map = "10,22", changeMap = "top", gather = true},
		{map = "10,21", changeMap = "top", gather = true},
		{map = "10,20", changeMap = "right", gather = true},
		{map = "11,20", changeMap = "right", gather = true},
		{map = "12,20", changeMap = "right", gather = true},
		{map = "13,20", changeMap = "top", gather = true},
		{map = "13,19", changeMap = "top", gather = true},
		{map = "13,18", changeMap = "top", gather = true},
		{map = "13,17", changeMap = "top", gather = true},
		{map = "13,16", changeMap = "top", gather = true},
		{map = "13,15", changeMap = "top", gather = true},
		{map = "13,14", changeMap = "top", gather = true},
		{map = "13,13", changeMap = "left", gather = true},
		{map = "12,13", changeMap = "top", gather = true},
		{map = "12,12", changeMap = "left", gather = true},
		{map = "11,12", changeMap = "left", gather = true},
		{map = "10,12", changeMap = "left", gather = true},
		{map = "9,12", changeMap = "left", gather = true},
		{map = "8,12", changeMap = "left", gather = true},
		{map = "7,12", changeMap = "bottom", gather = true},
		{map = "7,13", changeMap = "bottom", gather = true},
		{map = "7,14", changeMap = "bottom", gather = true},
		{map = "7,15", changeMap = "bottom", gather = true},
		{map = "7,16", changeMap = "bottom", gather = true},
		{map = "7,17", changeMap = "bottom", gather = true},
		{map = "7,18", changeMap = "right", gather = true},
		{map = "8,18", changeMap = "bottom", gather = true},
		{map = "8,19", changeMap = "right", gather = true},
		{map = "9,19", changeMap = "top", gather = true},
	}
	elseif (job:level(36) >= 70) and (job:level(36) < 80) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81}
	return {
		{map = "0,0", custom = scarafeuille},
		{map = "-1,24", changeMap = "right", gather = true},
		{map = "0,24", changeMap = "bottom", gather = true},
		{map = "0,25", changeMap = "bottom", gather = true},
		{map = "0,26", changeMap = "bottom", gather = true},
		{map = "0,27", changeMap = "bottom", gather = true},
		{map = "0,28", changeMap = "bottom", gather = true},
		{map = "0,29", changeMap = "bottom", gather = true},
		{map = "0,30", changeMap = "right", gather = true},
		{map = "1,30", changeMap = "bottom", gather = true},
		{map = "1,31", changeMap = "bottom", gather = true},
		{map = "1,32", changeMap = "bottom", gather = true},
		{map = "1,33", changeMap = "bottom", gather = true},
		{map = "1,34", changeMap = "left", gather = true},
		{map = "0,34", changeMap = "left", gather = true},
		{map = "-1,34", changeMap = "left", gather = true},
		{map = "-2,34", changeMap = "top", gather = true},
		{map = "-2,33", changeMap = "top", gather = true},
		{map = "-2,32", changeMap = "top", gather = true},
		{map = "-2,31", changeMap = "right", gather = true},
		{map = "-1,31", changeMap = "right", gather = true},
	}
	elseif (job:level(36) >= 80) and (job:level(36) < 90) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263}
	return {
		{map = "0,0", custom = scarafeuille},
		{map = "-2,28", changeMap = "top", gather = true},
		{map = "-1,24", changeMap = "left", gather = true},
		{map = "-2,24", changeMap = "left", gather = true},
		{map = "-3,24", changeMap = "left", gather = true},
		{map = "-4,24", changeMap = "bottom", gather = true},
		{map = "-4,25", changeMap = "left", gather = true},
		{map = "-5,25", changeMap = "bottom", gather = true},
		{map = "-5,26", changeMap = "bottom", gather = true},
		{map = "-5,27", changeMap = "left", gather = true},
		{map = "-6,27", changeMap = "left", gather = true},
		{map = "-7,27", changeMap = "bottom", gather = true},
		{map = "-7,28", changeMap = "bottom", gather = true},
		{map = "-7,29", changeMap = "bottom", gather = true},
		{map = "-7,30", changeMap = "bottom", gather = true},
		{map = "-7,31", changeMap = "bottom", gather = true},
		{map = "-7,32", changeMap = "right", gather = true},
		{map = "-6,32", changeMap = "top", gather = true},
		{map = "-6,31", changeMap = "right", gather = true},
		{map = "-5,31", changeMap = "bottom", gather = true},
		{map = "-5,32", changeMap = "right", gather = true},
		{map = "-4,32", changeMap = "right", gather = true},
		{map = "-3,32", changeMap = "top", gather = true},
		{map = "-3,31", changeMap = "left", gather = true},
		{map = "-4,31", changeMap = "top", gather = true},
		{map = "-4,30", changeMap = "right", gather = true},
		{map = "-3,30", changeMap = "right", gather = true},
		{map = "-2,30", changeMap = "right", gather = true},
		{map = "-1,30", changeMap = "top", gather = true},
		{map = "-1,29", changeMap = "left", gather = true},
		{map = "-2,29", changeMap = "left", gather = true},
		{map = "-3,29", changeMap = "top", gather = true},
		{map = "19,24", changeMap = "top", gather = true},
		{map = "-3,28", changeMap = "right", gather = true},
		{map = "-2,27", changeMap = "top", gather = true},
		{map = "-2,26", changeMap = "right", gather = true},
		{map = "-1,26", changeMap = "top", gather = true},
		{map = "-1,25", changeMap = "left", gather = true},
	}
	elseif (job:level(36) >= 90) and (job:level(36) < 100) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264}
	return {
		{map = "0,0", custom = scarafeuille},
		{map = "-1,24", changeMap = "right", gather = true},
		{map = "0,24", changeMap = "bottom", gather = true},
		{map = "0,25", changeMap = "bottom", gather = true},
		{map = "0,26", changeMap = "bottom", gather = true},
		{map = "0,27", changeMap = "bottom", gather = true},
		{map = "0,28", changeMap = "bottom", gather = true},
		{map = "0,29", changeMap = "bottom", gather = true},
		{map = "0,30", changeMap = "right", gather = true},
		{map = "1,30", changeMap = "bottom", gather = true},
		{map = "1,31", changeMap = "bottom", gather = true},
		{map = "1,32", changeMap = "bottom", gather = true},
		{map = "1,33", changeMap = "bottom", gather = true},
		{map = "1,34", changeMap = "left", gather = true},
		{map = "0,34", changeMap = "left", gather = true},
		{map = "-1,34", changeMap = "left", gather = true},
		{map = "-2,34", changeMap = "top", gather = true},
		{map = "-2,33", changeMap = "top", gather = true},
		{map = "-2,32", changeMap = "top", gather = true},
		{map = "-2,31", changeMap = "right", gather = true},
		{map = "-1,31", changeMap = "right", gather = true},
	}
	elseif (job:level(36) >= 100) and (job:level(36) < 110) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265}
	return {
		{map = "0,0", custom = scarafeuille},
		{map = "-1,24", changeMap = "left", gather = true},
		{map = "-2,24", changeMap = "left", gather = true},
		{map = "-3,24", changeMap = "left", gather = true},
		{map = "-4,24", changeMap = "bottom", gather = true},
		{map = "-4,25", changeMap = "left", gather = true},
		{map = "-5,25", changeMap = "bottom", gather = true},
		{map = "-5,26", changeMap = "bottom", gather = true},
		{map = "-5,27", changeMap = "bottom", gather = true},
		{map = "-5,28", changeMap = "left", gather = true},
		{map = "-6,28", changeMap = "top", gather = true},
		{map = "-6,27", changeMap = "left", gather = true},
		{map = "-7,27", changeMap = "bottom", gather = true},
		{map = "-7,28", changeMap = "bottom", gather = true},
		{map = "-7,29", changeMap = "bottom", gather = true},
		{map = "-7,30", changeMap = "bottom", gather = true},
		{map = "-7,31", changeMap = "bottom", gather = true},
		{map = "-7,32", changeMap = "right", gather = true},
		{map = "-6,32", changeMap = "right", gather = true},
		{map = "-5,32", changeMap = "right", gather = true},
		{map = "-4,32", changeMap = "right", gather = true},
		{map = "-3,32", changeMap = "top", gather = true},
		{map = "-3,31", changeMap = "left", gather = true},
		{map = "-4,31", changeMap = "top", gather = true},
		{map = "-4,30", changeMap = "right", gather = true},
		{map = "-3,30", changeMap = "right", gather = true},
		{map = "-2,30", changeMap = "right", gather = true},
		{map = "-1,30", changeMap = "top", gather = true},
		{map = "-1,29", changeMap = "left", gather = true},
		{map = "-2,29", changeMap = "left", gather = true},
		{map = "-3,29", changeMap = "left", gather = true},
		{map = "-4,29", changeMap = "top", gather = true},
		{map = "-4,28", changeMap = "right", gather = true},
		{map = "-3,28", changeMap = "right", gather = true},
		{map = "-2,28", changeMap = "top", gather = true},
		{map = "-2,27", changeMap = "top", gather = true},
		{map = "-2,26", changeMap = "right", gather = true},
		{map = "-1,26", changeMap = "top", gather = true},
	}
	elseif (job:level(36) >= 110) and (job:level(36) < 120) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266}
	return {
		{map = "0,0", custom = pandala},
		{map = "207619076",custom=sortir},
		{map = "206307842",changeMap="bottom",gather=true},
		{map = "20,-28",changeMap="bottom",gather=true},
		{map = "20,-27",changeMap="bottom",gather=true},
		{map = "20,-26",changeMap="left",gather=true},
		{map = "19,-26",changeMap="bottom",gather=true},
		{map = "19,-25",changeMap="bottom",gather=true},
		{map = "19,-24",changeMap="left",gather=true},
		{map = "18,-24",changeMap="bottom",gather=true},
		{map = "18,-23",changeMap="bottom",gather=true},
		{map = "18,-22",changeMap="right",gather=true},
		{map = "19,-22",changeMap="bottom",gather=true},
		{map = "19,-21",changeMap="right",gather=true},
		{map = "20,-21",changeMap="bottom",gather=true},
		{map = "20,-20",changeMap="right",gather=true},
		{map = "21,-20",changeMap="top",gather=true},
		{map = "21,-21",changeMap="right",gather=true},
		{map = "22,-21",changeMap="top",gather=true},
	}
	elseif (job:level(36) >= 120) and (job:level(36) < 130) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267}
	return {
		{map = "0,0",custom = eleveurs},
		{map = "-16,1", changeMap = "top", gather = true},
		{map = "-16,0", changeMap = "top", gather = true},
		{map = "-16,-1", changeMap = "top", gather = true},
		{map = "-16,-2", changeMap = "top", gather = true},
		{map = "-16,-3", changeMap = "right", gather = true},
		{map = "-15,-3", changeMap = "top", gather = true},
		{map = "-15,-4", changeMap = "right", gather = true},
		{map = "-14,-4", changeMap = "bottom", gather = true},
		{map = "-14,-3", changeMap = "right", gather = true},
		{map = "-13,-3", changeMap = "right", gather = true},
		{map = "-12,-3", changeMap = "top", gather = true},
		{map = "-12,-4", changeMap = "top", gather = true},
		{map = "-12,-5", changeMap = "left", gather = true},
		{map = "-13,-5", changeMap = "left", gather = true},
		{map = "-14,-5", changeMap = "top", gather = true},
		{map = "-14,-6", changeMap = "right", gather = true},
		{map = "-13,-6", changeMap = "top", gather = true},
		{map = "-13,-7", changeMap = "left", gather = true},
		{map = "-14,-7", changeMap = "top", gather = true},
		{map = "-14,-8", changeMap = "left", gather = true},
		{map = "-15,-8", changeMap = "bottom", gather = true},
		{map = "-15,-7", changeMap = "bottom", gather = true},
		{map = "-15,-6", changeMap = "bottom", gather = true},
		{map = "-15,-5", changeMap = "left", gather = true},
		{map = "-16,-5", changeMap = "top", gather = true},
		{map = "-16,-6", changeMap = "left", gather = true},
		{map = "-17,-6", changeMap = "top", gather = true},
		{map = "-17,-7", changeMap = "right", gather = true},
		{map = "-16,-7", changeMap = "top", gather = true},
		{map = "-16,-8", changeMap = "top", gather = true},
		{map = "-16,-9", changeMap = "left", gather = true},
		{map = "-17,-9", changeMap = "left", gather = true},
		{map = "-18,-9", changeMap = "left", gather = true},
		{map = "-19,-9", changeMap = "bottom", gather = true},
		{map = "-19,-8", changeMap = "right", gather = true},
		{map = "-18,-8", changeMap = "bottom", gather = true},
		{map = "-18,-7", changeMap = "bottom", gather = true},
		{map = "-18,-6", changeMap = "left", gather = true},
		{map = "-19,-6", changeMap = "top", gather = true},
		{map = "-19,-7", changeMap = "left", gather = true},
		{map = "-20,-7", changeMap = "bottom", gather = true},
		{map = "-20,-6", changeMap = "bottom", gather = true},
		{map = "-20,-5", changeMap = "bottom", gather = true},
		{map = "-20,-4", changeMap = "right", gather = true},
		{map = "-19,-4", changeMap = "bottom", gather = true},
		{map = "-19,-3", changeMap = "left", gather = true},
		{map = "-20,-3", changeMap = "left", gather = true},
		{map = "-21,-3", changeMap = "bottom", gather = true},
	}
	elseif (job:level(36) >= 130) and (job:level(36) < 140) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267,268}
	return {
		{map = "0,0",custom = lacDeCania},
		{map = "-3,-42", changeMap = "top", gather = true},
		{map = "-3,-43", changeMap = "top", gather = true},
		{map = "-3,-44", changeMap = "top", gather = true},
		{map = "-3,-45", changeMap = "top", gather = true},
		{map = "-3,-46", changeMap = "top", gather = true},
		{map = "-3,-48", changeMap = "top", gather = true},
		{map = "-3,-47", changeMap = "top", gather = true},
		{map = "-3,-49", changeMap = "top", gather = true},
		{map = "-3,-50", changeMap = "top", gather = true},
		{map = "-3,-51", changeMap = "top", gather = true},
		{map = "-3,-52", changeMap = "right", gather = true},
		{map = "-2,-52", changeMap = "right", gather = true},
		{map = "0,-52", changeMap = "right", gather = true},
		{map = "-1,-52", changeMap = "right", gather = true},
		{map = "1,-52", changeMap = "right", gather = true},
		{map = "2,-52", changeMap = "right", gather = true},
		{map = "3,-52", changeMap = "top", gather = true},
		{map = "3,-53", changeMap = "right", gather = true},
		{map = "4,-53", changeMap = "top", gather = true},
		{map = "4,-54", changeMap = "top", gather = true},
		{map = "4,-55", changeMap = "top", gather = true},
		{map = "4,-56", changeMap = "top", gather = true},
		{map = "4,-57", changeMap = "left", gather = true},
	}
	elseif (job:level(36) >= 140) and (job:level(36) < 150) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267,268,269}
	return {
		{map = "0,0",custom = pandala},
		{map = "207619076",custom=sortir},
		{map = "206307842",changeMap="right",gather=true},
		{map = "21,-29",changeMap="bottom",gather=true},
		{map = "21,-28",changeMap="bottom",gather=true},
		{map = "21,-27",changeMap="bottom",gather=true},
		{map = "21,-26",changeMap="bottom",gather=true},
		{map = "21,-25",changeMap="bottom",gather=true},
		{map = "21,-24",changeMap="right",gather=true},
		{map = "22,-24",changeMap="bottom",gather=true},
		{map = "22,-23",changeMap="right",gather=true},
		{map = "23,-23",changeMap="bottom",gather=true},
		{map = "23,-22",changeMap="left",gather=true},
		{map = "22,-22",changeMap="left",gather=true},
		{map = "21,-22",changeMap="left",gather=true},
		{map = "20,-22",changeMap="left",gather=true},
		{map = "19,-22",changeMap="top",gather=true},
		{map = "19,-23",changeMap="right",gather=true},
		{map = "18,-23",changeMap="top",gather=true},
		{map = "18,-24",changeMap="right",gather=true},
		{map = "19,-24",changeMap="right",gather=true},
		{map = "20,-24",custom=click,gather=true},
		{map = "21,-23",custom=lost,gather=true},
	}
	elseif (job:level(36) >= 150) and (job:level(36) < 160) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267,268,269,270}
	return {
		{map = "0,0",custom = lacDeCania},
		{map = "-3,-42", changeMap = "top", gather = true},
		{map = "-3,-43", changeMap = "top", gather = true},
		{map = "-3,-44", changeMap = "top", gather = true},
		{map = "-3,-45", changeMap = "top", gather = true},
		{map = "-3,-47", changeMap = "top", gather = true},
		{map = "-3,-46", changeMap = "top", gather = true},
		{map = "-3,-48", changeMap = "top", gather = true},
		{map = "20,-52", changeMap = "top", gather = true},
		{map = "-3,-49", changeMap = "right", gather = true},
		{map = "-2,-49", changeMap = "right", gather = true},
		{map = "-1,-49", changeMap = "right", gather = true},
		{map = "0,-49", changeMap = "right", gather = true},
		{map = "1,-49", changeMap = "top", gather = true},
		{map = "1,-50", changeMap = "top", gather = true},
		{map = "1,-51", changeMap = "top", gather = true},
		{map = "1,-52", changeMap = "right", gather = true},
		{map = "2,-52", changeMap = "right", gather = true},
		{map = "3,-52", changeMap = "top", gather = true},
		{map = "3,-53", changeMap = "right", gather = true},
		{map = "4,-53", changeMap = "top", gather = true},
		{map = "4,-54", changeMap = "top", gather = true},
		{map = "4,-55", changeMap = "top", gather = true},
		{map = "4,-56", changeMap = "top", gather = true},
		{map = "4,-57", changeMap = "left", gather = true},
	}
	elseif (job:level(36) >= 160) and (job:level(36) < 170) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267,268,269,270,271}
	return {
		{map = "0,0",custom = scarafeuille},
		{map = "-1,24", changeMap = "left", gather = true},
		{map = "-2,24", changeMap = "left", gather = true},
		{map = "-3,24", changeMap = "bottom", gather = true},
		{map = "-3,25", changeMap = "left", gather = true},
		{map = "-4,25", changeMap = "left", gather = true},
		{map = "-5,25", changeMap = "left", gather = true},
		{map = "-6,25", custom=click3, gather = true},
		{map = "-6,26", custom=click2, gather = true},
		{map = "-6,27", changeMap = "bottom", gather = true},
		{map = "-6,28", changeMap = "right", gather = true},
		{map = "-5,28", changeMap = "bottom", gather = true},
		{map = "-5,29", changeMap = "bottom", gather = true},
		{map = "-5,30", changeMap = "left", gather = true},
		{map = "-6,30", changeMap = "bottom", gather = true},
		{map = "-6,31", changeMap = "right", gather = true},
		{map = "-5,31", changeMap = "right", gather = true},
		{map = "-4,31", changeMap = "top", gather = true},
		{map = "-4,30", changeMap = "right", gather = true},
		{map = "-3,30", changeMap = "right", gather = true},
		{map = "-2,30", changeMap = "top", gather = true},
		{map = "-2,29", changeMap = "left", gather = true},
		{map = "-3,29", changeMap = "top", gather = true},
		{map = "-3,28", changeMap = "left", gather = true},
		{map = "-4,28", changeMap = "bottom", gather = true},
		{map = "-4,29", custom=lost, gather = true},
	}
	elseif (job:level(36) >= 170) and (job:level(36) < 180) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267,268,269,270,271,272}
	return {
		{map = "0,0",custom = otomai},
		{map = "-46,18", changeMap = "top", gather = true},
		{map = "-46,17", changeMap = "top", gather = true},
		{map = "-46,16", changeMap = "top", gather = true},
		{map = "-46,15", changeMap = "right", gather = true},
		{map = "-45,15", changeMap = "bottom", gather = true},
		{map = "-45,16", changeMap = "bottom", gather = true},
		{map = "-45,17", changeMap = "bottom", gather = true},
		{map = "-45,18", changeMap = "bottom", gather = true},
		{map = "-47,19", changeMap = "left", gather = true},
		{map = "-48,19", changeMap = "top", gather = true},
		{map = "-48,18", changeMap = "top", gather = true},
		{map = "-48,17", changeMap = "top", gather = true},
		{map = "-48,16", changeMap = "top", gather = true},
		{map = "-48,15", changeMap = "top", gather = true},
		{map = "-48,14", changeMap = "right", gather = true},
		{map = "-47,14", changeMap = "right", gather = true},
		{map = "-46,14", changeMap = "top", gather = true},
		{map = "-46,13", changeMap = "left", gather = true},
		{map = "-47,13", changeMap = "top", gather = true},
		{map = "-47,12", changeMap = "top", gather = true},
		{map = "-47,11", changeMap = "left", gather = true},
		{map = "-48,11", changeMap = "left", gather = true},
		{map = "-49,11", changeMap = "top", gather = true},
		{map = "-49,10", changeMap = "top", gather = true},
		{map = "-49,9", changeMap = "top", gather = true},
		{map = "-49,8", changeMap = "top", gather = true},
		{map = "-49,7", changeMap = "left", gather = true},
		{map = "-50,7", changeMap = "left", gather = true},
		{map = "-51,7", changeMap = "top", gather = true},
		{map = "-51,6", changeMap = "top", gather = true},
		{map = "-51,4", changeMap = "top", gather = true},
		{map = "-51,5", changeMap = "top", gather = true},
		{map = "-51,3", changeMap = "left", gather = true},
		{map = "-52,3", changeMap = "left", gather = true},
		{map = "-53,3", changeMap = "left", gather = true},
		{map = "-54,3", changeMap = "left", gather = true},
		{map = "-55,3", changeMap = "left", gather = true},
		{map = "-56,3", changeMap = "left", gather = true},
		{map = "-57,3", changeMap = "left", gather = true},
		{map = "-58,3", changeMap = "top", gather = true},
		{map = "-58,2", changeMap = "top", gather = true},
		{map = "-29,7", changeMap = "top", gather = true},
		{map = "-58,1", changeMap = "left", gather = true},
		{map = "-59,1", changeMap = "bottom", gather = true},
		{map = "-59,2", changeMap = "left", gather = true},
		{map = "-60,2", changeMap = "bottom", gather = true},
		{map = "-60,3", changeMap = "bottom", gather = true},
		{map = "-60,4", changeMap = "bottom", gather = true},
		{map = "-60,5", changeMap = "right", gather = true},
		{map = "-59,5", changeMap = "bottom", gather = true},
		{map = "-59,6", changeMap = "bottom", gather = true},
		{map = "-59,7", changeMap = "bottom", gather = true},
		{map = "-59,8", changeMap = "bottom", gather = true},
		{map = "-59,9", changeMap = "bottom", gather = true},
		{map = "-45,19", changeMap = "bottom", gather = true},
		{map = "-45,20", changeMap = "left", gather = true},
		{map = "-46,20", changeMap = "bottom", gather = true},
		{map = "-46,21", changeMap = "bottom", gather = true},
		{map = "-46,22", changeMap = "left", gather = true},
		{map = "-47,22", changeMap = "top", gather = true},
		{map = "-47,21", changeMap = "top", gather = true},
		{map = "-47,20", changeMap = "top", gather = true},
		{map = "-35,17", changeMap = "bottom", gather = true},
		{map = "-59,10", changeMap = "bottom", gather = true},
		{map = "-59,11", changeMap = "bottom", gather = true},
		{map = "-59,12", changeMap = "bottom", gather = true},
		{map = "-59,13", changeMap = "bottom", gather = true},
		{map = "-59,14", changeMap = "bottom", gather = true},
		{map = "-59,15", changeMap = "bottom", gather = true},
		{map = "-59,16", changeMap = "bottom", gather = true},
		{map = "-59,17", changeMap = "bottom", gather = true},
		{map = "-59,18", changeMap = "bottom", gather = true},
		{map = "-59,19", changeMap = "bottom", gather = true},
		{map = "-59,20", changeMap = "bottom", gather = true},
		{map = "-59,21", changeMap = "bottom", gather = true},
		{map = "-59,22", changeMap = "bottom", gather = true},
		{map = "-59,23", changeMap = "bottom", gather = true},
		{map = "-59,24", changeMap = "right", gather = true},
		{map = "-58,24", changeMap = "bottom", gather = true},
		{map = "-58,25", changeMap = "bottom", gather = true},
	}
	elseif (job:level(36) >= 180) and (job:level(36) < 190) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267,268,269,270,271,272,273}
	return {
		{map = "0,0", custom = frigost},
		{map = "-78,-41", changeMap = "top", gather = true},
		{map = "-78,-42", changeMap = "top", gather = true},
		{map = "-78,-43", changeMap = "top", gather = true},
		{map = "-78,-44", changeMap = "top", gather = true},
		{map = "-78,-45", changeMap = "top", gather = true},
		{map = "-78,-46", changeMap = "right", gather = true},
		{map = "-77,-46", changeMap = "right", gather = true},
		{map = "-76,-46", changeMap = "right", gather = true},
		{map = "-75,-46", changeMap = "right", gather = true},
		{map = "-73,-46", changeMap = "right", gather = true},
		{map = "-74,-46", changeMap = "right", gather = true},
		{map = "-72,-46", changeMap = "right", gather = true},
		{map = "-71,-46", changeMap = "right", gather = true},
		{map = "-70,-46", changeMap = "right", gather = true},
		{map = "-69,-46", changeMap = "top", gather = true},
		{map = "-69,-47", changeMap = "top", gather = true},
		{map = "-69,-48", changeMap = "top", gather = true},
		{map = "-69,-49", changeMap = "top", gather = true},
		{map = "-69,-50", changeMap = "top", gather = true},
		{map = "-69,-51", changeMap = "right", gather = true},
		{map = "-68,-51", changeMap = "top", gather = true},
		{map = "-68,-52", changeMap = "top", gather = true},
		{map = "-68,-53", changeMap = "top", gather = true},
		{map = "-49,-54", changeMap = "top", gather = true},
		{map = "-68,-54", changeMap = "right", gather = true},
		{map = "-67,-54", changeMap = "right", gather = true},
		{map = "-66,-54", changeMap = "bottom", gather = true},
		{map = "-66,-53", changeMap = "right", gather = true},
		{map = "-65,-53", changeMap = "right", gather = true},
		{map = "-64,-53", changeMap = "right", gather = true},
		{map = "-63,-53", changeMap = "top", gather = true},
		{map = "-63,-54", changeMap = "top", gather = true},
		{map = "-63,-55", changeMap = "top", gather = true},
	}
	elseif (job:level(36) >= 190) and (job:level(36) < 200) then
		ELEMENTS_TO_GATHER = {75,71,74,77,76,78,79,81,263,264,265,266,267,268,269,270,271,272,273,274}
	return {
		{map="0,0",custom=lacDeCania},
		{map = "-3,-42", changeMap = "top", gather = true},
		{map = "-3,-43", changeMap = "top", gather = true},
		{map = "-3,-44", changeMap = "top", gather = true},
		{map = "-2,-46", changeMap = "top", gather = true},
		{map = "-3,-45", changeMap = "top", gather = true},
		{map = "-3,-46", changeMap = "right", gather = true},
		{map = "-2,-47", changeMap = "top", gather = true},
		{map = "-2,-48", changeMap = "top", gather = true},
		{map = "-2,-49", changeMap = "top", gather = true},
		{map = "-2,-51", changeMap = "top", gather = true},
		{map = "-2,-50", changeMap = "top", gather = true},
		{map = "-2,-52", changeMap = "right", gather = true},
		{map = "-1,-52", changeMap = "right", gather = true},
		{map = "0,-52", changeMap = "right", gather = true},
		{map = "1,-52", changeMap = "right", gather = true},
		{map = "3,-53", changeMap = "right", gather = true},
		{map = "4,-53", changeMap = "top", gather = true},
		{map = "4,-54", changeMap = "top", gather = true},
		{map = "4,-55", changeMap = "top", gather = true},
		{map = "4,-56", changeMap = "top", gather = true},
		{map = "4,-57", changeMap = "left", gather = true},
		{map = "2,-52", changeMap = "right", gather = true},
		{map = "3,-52", changeMap = "top", gather = true},
	}
end
end

function bank()
	return {
		{map="0,0",custom=astrub},
		{map="5,-18",changeMap="left"},
		{map="191104002",changeMap="289"},
		{map="192415750",custom=hiboux,changeMap="424"},
	}
end